### ISSUE TITLE
Add parameter to disable AI Air support

### ISSUE THREAD

**Issue by SyniRon** [Savage-Game-Design/Mike-Force#1]
**Is your feature request related to a problem? Please describe.**
In a multiplayer system having AI Air support available to RTOs feels weird. Especially considering the incredibly short cooldown on reusing it. An RTO can just pepper an area with nearly unlimited Air Support making CAS flown by the Green Honets basically redundant and unnecessary.

**Describe the solution you'd like**
Add a parameter that enables or disables the Air Support system.

**Describe alternatives you've considered**
An alternative would be a parameter that changes the cooldown multiplier or something similar.

**Additional context**
N/A

**Comment by Spoffy** [comment]
I can certainly look into the feasibility of this in the future :)

**Comment by Spoffy** [comment]
Thanks for the suggestion, this has been confirmed and will be added in a future release, if possible!

**Comment by Alablm** [comment]
This has been implemented in the latest internal version of Mike Force.

**Comment by Alablm** [comment]
Fixed in release 0.66.02
