### ISSUE TITLE
Admin has no arsenal 

### ISSUE THREAD

**Issue by JDownward** [Savage-Game-Design/Mike-Force#10]
when logged in admin the arsenal doesn't allow you to get anything.

**Comment by TheBlueFang** [comment]
We're having the same bug. It is happening on a dedicated server.

**Arma/Server version:** 2.04.147540
**Server:** Dedicated
**Headless clients:** none
**Scenario version:** Beta v0.65.03 (downloaded from workshop)
**CDLC:** SOG Prairie Fire DLC
**Mods:** none

**How to replicate:**
Setup dedicated server and run Mike Force Beta v0.65.03. Login as admin and enter the arsenal.

**Comment by Spoffy** [comment]
This is confirmed - there's a known fix, it just needs implementing!

**Comment by Alablm** [comment]
A fix for this has been implemented in the latest internal version of Mike Force.

**Comment by Alablm** [comment]
Fixed in release 0.66.02
