### ISSUE TITLE
Cant capture an area (not sure if bug or we are doing something wrong)

### ISSUE THREAD

**Issue by Rex2250** [Savage-Game-Design/Mike-Force#101]
**Describe the bug**
A few if friends and I were playing Mike Force, we have had several times where we would clear out an area, Saigon for example, we would clear out all AA, Artillery, HQ, and fully cleared any counter attacks that happened. The area would still not be counted at captured and remained red. Is there something we are missing or are the capture areas glitched sometimes?

**To Reproduce**
As said above, cleared out everything including counter attacks, but would not capture

**Expected behaviour**
Expected the area to capture after everything was destroyed, including counter attacks, we stood there for an hour with nothing happening

**Screenshots**
I do not have any screenshots

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): Cam Lao Nam

* [ ] Official Server
* [ ] Official InDev Server
* [X] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
CBA_A3
Task Force Arrowhead Radio
Enhanced movement
DUI- Squad Radar
Tactical Hand Signals
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 
I do not remember exactly when it happened but it has happened multiple times the past few days

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Alablm** [comment]
Zones need to have a task on them to be capturable

**Comment by Spoffy** [comment]
Closing as not enough information, or as Alablm said, zones require a task to be capturable!
