### ISSUE TITLE
AI getting in loaded static weapons

### ISSUE THREAD

**Issue by AlexFilippov30** [Savage-Game-Design/Mike-Force#104]
**Describe the bug**
AI somehow can man static weapons(mg,mortar) and use them, when they are loaded into logistics inventory. If AI managed to man static weapon, it uses it, while being invisible. To stop them you need to unload static weapon and kill gunner.

**To Reproduce**
Load static weapon into helicopter or truck and let AI come close to vehicle.

**Expected behaviour**
Find out, how AI can man loaded static weapons and fix it.

**Environment (please complete the following information):**
Version: v0.65.03
Map (specify if Altis Blufor): Cam Lao Nam

* [+] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

**Comment by Alablm** [comment]
Closing as this has been fixed
