### ISSUE TITLE
Server #7 - Artillery is Bugged in Saigon. Server #5 also needs a reset, the map is controlled.

### ISSUE THREAD

**Issue by MattyGG** [Savage-Game-Design/Mike-Force#106]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):

**Expected behaviour**
- The artillery on Server #7 in Saigon appears to be bugged; no one can find it nor destroy it and the Tasking is stuck on "Destroy Sites"

- Server #5 needs reset, the map is entirely controlled by friendly forces.

**Screenshots**

**Environment (please complete the following information):**
Version: MikeForce
Map (specify if Altis Blufor): Cam_Lao_Nam 

* [X] Official Server

**Comment by Spoffy** [comment]
Closing as this is a server issue, not a gamemode issue! That said, we've got fixes in the works for both of these problems!
