### ISSUE TITLE
Search and Destroy

### ISSUE THREAD

**Issue by apwallis** [Savage-Game-Design/Mike-Force#109]
**Is your feature request related to a problem? Please describe.**

1. The concept of "conquering the map" feels wrong in the context of Vietnam.
2. Multiple possible active AOs quite often turns into a clusterfuck on open servers. You get people going all over the place, the "mission" literally descends into chaos. 
3. Too much CAS makes the game either boring or a friendly fire fest for everyone who isn't CAS (about half the server pop usually given how much CAS is available).
4. Spike force has no useful application. Give them missions sure, but what's the point? We already have everything plus some.

**Describe the solution you'd like**
Back in the day there was a a game mode called Search and Destroy (amongst other things). There would be one main AO and one side mission active at once. When completed, it would be removed from the map and another one would spawn in another  random location. This would continue indefinitely until the server admin decided to reset it.
I feel this alone would solve issue 1&2. S&D ended up being kinda dull in of it self. However I feel the it would work really well within the context of MikeForce systems. Mike force gives that additional complexity and ultimately a "point" to it via ranks etc.

The side missions would then be for Spike Force and only visible to them. And like in S&D the rewards for completing them would be "rare" vehicles. Such as CAS. I.E. radically reduce the CAS available normally, and then "unlock" limited amounts of it via spike force side missions. 
**Describe alternatives you've considered**
Maybe have more than 1 active AO if you are really into the multiple AO thing. But definitely ditch the whole conquer the map thing. It's the most immersion breaking thing about the mode imo.

**Additional context**
None that I can think of

**Comment by Spoffy** [comment]
Some really interesting suggestions in here - I'll leave this open to revisit while we design our second big update, which will touch on a lot of these elements!
