### ISSUE TITLE
F-4 phantom, cannot use CCRP bomb computer do to the way the loadouts  are set up. (really simple fix)

### ISSUE THREAD

**Issue by EpiicPenguin** [Savage-Game-Design/Mike-Force#111]
**Describe the bug**
The F-4 phantom loadouts bombs are linked to the radar officers seat (labeled gunners seat in arma). in the phantom there is a super cool CCRP computer modeled into the cockpit, but it only works if the pilot has control over the weapons in pylon manager.
all the loadouts for the Phantom in MF have the gunners seat in control of the bombs. you can drop bombs by selecting manual fire but the CCRP computer is scripted to use the weapons assigned to the pilot does not use the correct mode or trajectory calculations if using the manual fire option. (you can get the ccrp to show up by selecting rockets but the trajectory will be all wrong for bombs.)

**To Reproduce**
get in phantom on an offical MF server, select any loadout from master arm. 

**Expected behaviour**
bombs + all weapons should be linked to the pilot seat in loadouts, so the CCRP computer behave's properly 

**Environment (please complete the following information):**
Version: 65.03
Map (specify if Altis Blufor): offical MF server 6 and 12, are what i play on but all of them have this. 

* [x ] Official Server

**Additional context**

you can test this out in the editor by setting pilot seat to control all weapons in pylonmanager. you should just need to change the default server loadouts.  the CCRP comptuer is dead center when in the cockpit, just bellow the hud. shift click on map to set a target point then, use the info given to guide the plane to the release point.

**Comment by MaartenWesterdijk** [comment]
Won't be changed in the DLC, a mission sided fix could be considered. 

Gitlab ref #1228

**Comment by Alablm** [comment]
Wont be changed in mission.
