### ISSUE TITLE
if you destroy a vehicle on its respawn point it will respawn on its own wreck causing it to blow up again, in an infinite loop.

### ISSUE THREAD

**Issue by EpiicPenguin** [Savage-Game-Design/Mike-Force#112]
**Describe the bug**
if you destroy a vehicle on its respawn point it will respawn on its own wreck causing it to blow up again, in an infinite loop. 

**To Reproduce**
blow up one of the jeeps at spike team camp on its spawn location, the jeep will respawn and because its own wreck is in the way immediately blow up again, creating a infinite loop that only stops by random chance. 

**Environment (please complete the following information):**
Version: 65.03
Map: MF official server 6

* [x ] Official Server

Additional mods:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**
just add a pause in the script before vehicle respawn to let the wreck delete before the new vehicle spawns in. i tested this with the jeeps at spike team camp, but it happens with any of the automatically respawning vehicles/ helicopters

**Comment by Alablm** [comment]
Fixed in release 0.66.02
