### ISSUE TITLE
Type 63 Tank locked

### ISSUE THREAD

**Issue by Alablm** [Savage-Game-Design/Mike-Force#114]
**Describe the bug**
The type 63 tank at the ACAV base is locked to opfor by arsenal.hpp

**To Reproduce**
Attempt to get in the drivers seat of the Type 63

**Expected behavior**
Type 63 should be drivable

**Screenshots**
https://puu.sh/HT9PS/18e6595e6d.png

**Environment (please complete the following information):**
Version: v0.65.03
Map (specify if Altis Blufor): 

* [x] Official Server
* [x] Official InDev Server
* [x] Private dedicated server
* [x] Private dedicated server with Headless client(s)
* [x] LAN Hosted

Additional mods:
N/A  
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 
N/A
**Additional context**
Lock is caused by line 1155 of arsenal.hpp `{"vn_o_armor_type63_01",{5,-1,-1,-1}},`
The second (west) value needs to be changed to a number other than -1 to resolve this issue.

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.
N/A

**Comment by DanThomas64** [comment]
Cannot replicate this issue. The value of -1 for WEST means that the vehicle has no Rank Lock and so should be available to anyone who is in ACAV.

**Comment by Alablm** [comment]
Confirming, no longer able to replicate in either the editor or dedicated hardware.

Arma is weird.
