### ISSUE TITLE
Server#02 is bugged and wont finish, we have tried varies thing including vote restart but no luck Ithnk it needs a server restart.  thamk you we love the game

### ISSUE THREAD

**Issue by VikingThor12** [Savage-Game-Design/Mike-Force#115]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

* [x] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Spoffy** [comment]
This should be reported in our Discord in the future, as you'll get a much faster response!
https://discord.gg/KwNmfjUK3a
