### ISSUE TITLE
Master Arm Menu bug

### ISSUE THREAD

**Issue by backseat1-1** [Savage-Game-Design/Mike-Force#117]
**Describe the bug**
Pilots are sometimes unable to access Master Arms menu at Pleiku.

**To Reproduce**
Trigger unknown. May be something to do with withstanding in chopper or having co-pilot present. Respawning seems to fix this problem

**Expected behaviour**
Master Arm access at Pleiku

Pleiku Airbase
Version: v0.65.03

Official Server 1

No mods
    
Multiple occurrences for myself, and other pilots

**Comment by Alablm** [comment]
Not enough info/cant reproduce/cdlc, closing
