### ISSUE TITLE
Chopping down trees

### ISSUE THREAD

**Issue by joar** [Savage-Game-Design/Mike-Force#119]
**Is your feature request related to a problem? Please describe.**
Sometimes trees are in the wrong spot, and you need to remove them, some examples are:
- Clearing a landing pad or approach path for helicopters in a FOB.
- Making sure you're able to have a clear view out of a FOB on any attacking forces in a FOB.

**Describe the solution you'd like**
There are axes in the CDLC, I'd like to be able to chop down trees with them.

**Describe alternatives you've considered**
Calling in daisy cutters is a possible workaround, but it's impossible if the FOB has already been built, and it's overkill if you only need to remove a couple of trees.

**Additional context**

**Comment by Spoffy** [comment]
This is already in development, you might be pleased to know! :)

**Comment by Alablm** [comment]
Closing this as it is now in game
