### ISSUE TITLE
Having trouble hosting Dedicated Server with latest DLC

### ISSUE THREAD

**Issue by TMLSniper** [Savage-Game-Design/Mike-Force#12]
Description:
So my friend has a dedicated server and we want to get the server out with the new Mike Force mission. We have everything downloaded but when we launch into the game all the roles are gone and there is a text on the bottom right that says something about American Flags. I wish I could get the full text but my friend stayed up all night trying to fix this and the server is down and I can't get it. We've tried to update through SteamCMD but that didn't work or could have done it wrong. Any help is very much appreciated. Thanks

Reproduce:
Every time we launch Server this happens

Expected Behavior: 
It doesn't crash game or anything you just can't do anything

No screen shots sadly

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): Cam Lao Nam  

* [ ] Official Server
* [ ] Official InDev Server
* [X] Private dedicated server (I don't know which two)
* [X ] Private dedicated server with Headless client(s) (I don't know which two)
* [ ] LAN Hosted

Additional mods:

Time the bug occurred (Please leave in GMT+0): 5/7/21 1:30 CST

**Additional context**
What we tried to fix:
Update through SteamCMD
Unload all mods
Download DLC assets and implement into server(something along those lines)

**Comment by Spoffy** [comment]
Hi @TMLSniper!
I'm not sure this is the right place to get this problem solved! Can I recommend https://community.sogpf.com or visiting our Discord at https://discord.gg/hCpX9Q3fvZ
