### ISSUE TITLE
Cutting elephant grass

### ISSUE THREAD

**Issue by joar** [Savage-Game-Design/Mike-Force#120]
**Is your feature request related to a problem? Please describe.**
There are a few issues with elephant grass and other bushes, but especially elephant grass:
- VCs have an unfair advantage whenever there's elephant grass around, they mostly ignore it and just shoot you through it.
- It makes it much harder to build, because the `linesIntersect...` hits the elephant grass instead of the ground below it.

**Describe the solution you'd like**
I'd like to be able to chop down elephant grass and other small bushes with the machete in order to clear an area around and inside a FOB from the pesky things.

**Describe alternatives you've considered**
Daisy cutters. Dropping crates works on bushes, but not on elephant grass, because elephant grass can't be touched.

**Comment by Alablm** [comment]
Closing as this is now in game
