### ISSUE TITLE
Adding a Zeus to LAN/Local server Hosted Games

### ISSUE THREAD

**Issue by LordBoxius** [Savage-Game-Design/Mike-Force#121]
**Is your feature request related to a problem? Please describe.**
It would useful to be able to fix issues with the AO's and placement of the AA/Arty etc...

**Describe the solution you'd like**
An additional slot for a Zeus player to make the game flow, and add in extra enemy units.

**Describe alternatives you've considered**
I do not know of any alternatives.

**Additional context**
None.

**Comment by Spoffy** [comment]
This should already be possible by logging in as an admin! 🙂
