### ISSUE TITLE
Where's the Bible?

### ISSUE THREAD

**Issue by rogerxx** [Savage-Game-Design/Mike-Force#123]
We have whiskey, hot sauce, hot dogs & beans, so where's the Bible?

Bibles are suppose to bring good luck, or account for lucky catches with bullets right?

**Comment by Alablm** [comment]
This is completely irrelevant to the Mike Force mission. If you feel that something should be added to the SOGPF DLC it should be suggested on the feature request section of the Savage Forums. https://community.sogpf.com/forums/2-S4-Gear-amp-Assets
