### ISSUE TITLE
vn_mf_targetNumberOfActiveZones broken

### ISSUE THREAD

**Issue by ReapShkii** [Savage-Game-Design/Mike-Force#124]
![picture of code](https://user-images.githubusercontent.com/91512256/135011073-8653fe05-6215-400b-8669-95ba8ab0246a.png)

This line is broken. I keep getting like 5 Active AOs. I only want one to be active at a time so we can promote full server Teamwork

**Comment by ReapShkii** [comment]
located in para_server_init.sqf

**Comment by ReapShkii** [comment]
Can I get a work around or something added to params settings so I can limit AOs without having to rewrite the config for connection zones? @BadWolf64

**Comment by Alablm** [comment]
The work around right now would be to change the zone config unfortunately. We are looking into it, but unfortunately it hasn't been an easy fix. Hopefully we'll have something not too long after the holidays, but I can't make any promises unfortunately.

**Comment by ReapShkii** [comment]
@Alablm I'm currently reworking the zone config. unfortunately it'll be linear instead of random but one AO at a time reinforces Teamwork of the whole server so it'll be good enough.

**Comment by Alablm** [comment]
@ReapShkii If you don't mind sharing it would be kind of you to post that config here when you're done with it, as I'm sure there are others who would agree with you

**Comment by DanThomas64** [comment]
I have been tracking this down. It's not as straight forward as I first thought. There is not a real work around other than the one you are already using. 

When I fix this a param will be included with it so that it can be changed in game.

**Comment by ReapShkii** [comment]
@Alablm yeah I'll post it. All I did was add all the aos and connect them one at a time. It's unfortunately linear if people don't mind it as an alternative. My server doesn't seem to mind. I attach here and if you like could make it more accessible to others.

**Comment by ReapShkii** [comment]
[map_config.zip](https://github.com/Savage-Game-Design/Mike-Force/files/7777226/map_config.zip)

includes init with first AO fixed to Ban Hoang

**Comment by Alablm** [comment]
Closing this, we're not going for a fix on this specific issue, but something similar is coming.
