### ISSUE TITLE
New Assets aren't configured correctly

### ISSUE THREAD

**Issue by warlocc** [Savage-Game-Design/Mike-Force#125]
Today's update (September 30) added new assets. None are configured correctly in order to show up in arsenals.

![7e1cf87600d7e13d0ddb9ba1a79a69f4](https://user-images.githubusercontent.com/41884701/135521768-8101a717-8241-4c13-bea8-dd6b618f29df.jpg)
s

**Comment by DanThomas64** [comment]
Can you please provide more information about your server set up and configuration?

**Comment by warlocc** [comment]
No server. This is single player in the editor. Spawned a dude and opened the arsenal on him. Tried it with the compat mod and with the DLC directly.

Also, when opening the editor, the new map (Khe Sanh) doesn't show up either.

**Comment by DanThomas64** [comment]
Okay this seems to be a CDLC issue and not a MF specific issue. I would verify the integrity of your arma game files in steam and see if the issue persists. 

If it does then try testing the arsenal with a mission that is not MF.

**Comment by Alablm** [comment]
Closing - Can not replicate/cdlc
