### ISSUE TITLE
Logging in to admin causes all weapons in the Arsenal to disappear.

### ISSUE THREAD

**Issue by Novakore** [Savage-Game-Design/Mike-Force#126]
Entre into Mike Force is fine on a private dedicated server. However, after logging into the admin to access Zeus items, the entire arsenal becomes unavailable to the admin. All weapons and items are rendered inaccessible to the admin. 

![20211004233733_1](https://user-images.githubusercontent.com/91902113/135881261-4e9e291f-641b-4eed-b369-4d759014f1e9.jpg)

Another noteworthy bug that was found on my private dedicated server was that after the F-4 Phantom is destroyed by a player, the radio support function used by the radio operator no longer has access to air support or fire support functions. 
![20211004233710_1](https://user-images.githubusercontent.com/91902113/135881170-fc6398c2-3e37-406e-b97c-f3a6c266c22c.jpg)

**Comment by DanThomas64** [comment]
This is known issue.
https://github.com/Savage-Game-Design/Mike-Force/issues/10
Thank you for the report. We are working on a solution to this issue.

**Comment by Novakore** [comment]
Ah, understood. What about the air support function disappearing completely? As far as I can tell, it only happened after the F-4 Phantom crashed into the ocean beyond map boundaries. And when a To-201 Shikra was spawned.
