### ISSUE TITLE
Call for AI fire support not functioning as it used to.

### ISSUE THREAD

**Issue by Novakore** [Savage-Game-Design/Mike-Force#127]
**Describe the bug**
Radio support function ceased to function, completely removing radio operators ability to call in AI fire support.

**To Reproduce**
A player on a private dedicated server crashed the available F-4 phantom out of boundaries in the ocean, and a To-201 Shikra was spawned before radio support functionality ceased. Friendly fire was also caused to admin before it stopped working. 

**Expected behaviour**
Not sure. I expected the air support function to work, allowing the radio operator to call in fire support when needed, as seen in previous versions of Mike Force.

**Screenshots**
![20211013021146_1](https://user-images.githubusercontent.com/91902113/137008281-42d46cec-1510-4a50-b2b8-50ebd044a248.jpg)

**Environment (please complete the following information):**
Version: Latest version, unknown code, recently downloaded off steam workshop.
Map (specify if Altis Blufor): Cam Lao Nam

* [ ] Official Server
* [ ] Official InDev Server
* [/] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
Enhanced Movement, Enhanced Movement rework, DUI Squad Radar, CBA_A3, Remove Stamina.

**Comment by Alablm** [comment]
The server you're playing on has disabled the air support module of the RTO system.
