### ISSUE TITLE
SPIKE Force Medical Slick Spawns slightly into the ground.

### ISSUE THREAD

**Issue by LoFiVietNam** [Savage-Game-Design/Mike-Force#129]
**Describe the bug**
SPIKE Force Medical chopper spawns a few inches into the ground. If not destroyed it will be heavily damaged with tail rotor issues.

**To Reproduce**
Respawning SPIKE Force medical chopper can lead to the medical chopper clipping to about the cabin level into the ground, other times it bounces and sustains damage.

**Expected behaviour**
I understand Arma is just being Arma, but would love to see if it can be adjusted so SPIKE Force doesn't have to deal with a damaged Helo always sitting in the base!

**Environment (please complete the following information):**
Version: 
0.66.0.1 Cam Lao Nam 

* [X ] Official InDev Server

**Comment by Alablm** [comment]
Spike team does not have any helicopters at their base. You're going to need to be more specific

**Comment by Alablm** [comment]
Closing due to lack of followup
