### ISSUE TITLE
Cdlc unconscious module

### ISSUE THREAD

**Issue by Willparker666** [Savage-Game-Design/Mike-Force#13]
**Describe the bug**
Can't turn off Cdlc unconscious module, this means ace medical is kinda ruined in liberation

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant): use liberation cam lao map on liberation server with ace medical enabled.

**Expected behaviour**
a simple addon option to disable the cdlc module so only ace is used.

**Screenshots**
N/a

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): Cam Lao

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ Y] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
Ace
AceX
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by SyniRon** [comment]
This is the issue tracker for the mike force mission file, not for liberation or the CDLC. 

However you can easily disable the revive module on the liberation file by simply deleting the module from the map in eden editor

**Comment by Spoffy** [comment]
Closing this because it's not an issue for Mike Force (thanks for handling this @peakzero)!
You can report it at:
community.sogpf.com/
Or
https://github.com/KillahPotatoes/KP-Liberation

Thanks for taking the time to write the report though! 👍

**Comment by Willparker666** [comment]
Thank you, that answered my question perfectly even though I was in the wrong place. thx again
