### ISSUE TITLE
Build mode persists when you enter vehicles, lets you build floating structures.

### ISSUE THREAD

**Issue by plebeianjay** [Savage-Game-Design/Mike-Force#130]
You're able to build free-floating structures using a combination of two issues that may be unintended. The two issues would be keeping build-mode active while entering vehicles and using vehicles as anchor points to build structures off of.

To reproduce:
Open up the building menu as an engineer, after selecting an object to build get in the pilot seat of a Cayuse. The building mode will stay active once in the vehicle, following your crosshair and allowing you to anchor the structure to your Cayuse while flying. I was able to produce this in both private and official servers.

Expected behavior:
Structures that normally need to be anchored to the ground will be built floating in the air.

Screenshots/Video
https://cdn.discordapp.com/attachments/309753216026017793/900250944468570113/unknown.png
https://cdn.discordapp.com/attachments/309753216026017793/900251118330855505/unknown.png
6 minute video of the process: https://www.youtube.com/watch?v=kPoInjKvlJA

**Comment by Alablm** [comment]
Thanks for the detailed report Jay

**Comment by Alablm** [comment]
This has been fixed in the latest internal version of Mike Force

**Comment by Alablm** [comment]
Fixed in release 0.66.02
