### ISSUE TITLE
Change default snake bite chance

### ISSUE THREAD

**Issue by DrymarchonShaun** [Savage-Game-Design/Mike-Force#132]
**Describe the solution you'd like**
Set default snake bite chance to 25%

**Additional context**
I've seen some complaints that snake bites occur too frequently, and speaking from a realism point of view, there are around 200 species of snakes in vietnam, ~25% of which are venomous, meaning at most the default percentage chance of a bite should be 25%, because simply speaking, that is the highest chance that is realistically possible. On top of that, even if you get within a meter of a venomous snake, it's not necessarily going to bite you. Most snakes would just stop moving and wait for you to move on instead of biting, so really that percentage would be even lower than 25%.

**Comment by Alablm** [comment]
A parameter for this has been added in the latest internal build of Mike Force

**Comment by Alablm** [comment]
Fixed in release 0.66.02
