### ISSUE TITLE
Vietnam era Medikit doesn't let you withstand on Khe Sanh, works as intended on Cam Lao

### ISSUE THREAD

**Issue by plebeianjay** [Savage-Game-Design/Mike-Force#134]
If you have the Vietnam era medikit equipped, and no first aids, on Khe Sanh and try to withstand you receive the message "you do not have the required 4 first aid kits to withstand". With the same loadout on Cam Lao Nam you are able to withstand and get the message "you have used your medikit to withstand, it has not been consumed".

Equip a Vietnam era medikit on Khe Sanh, make sure you have no first aids equipped. Die and try to withstand, it won't let you. Repeating the same process on Cam Lao lets you withstand.

Screenshot: https://cdn.discordapp.com/attachments/309753216026017793/916754850807709736/unknown.png

Map: Khe Sanh, Cam Lao Nam

**Comment by Alablm** [comment]
Fixed in latest dev build

**Comment by Alablm** [comment]
Fixed in release 0.66.02
