### ISSUE TITLE
Arsenal Issue - only basic gear showing after mission running for several hours.

### ISSUE THREAD

**Issue by R0adki11** [Savage-Game-Design/Mike-Force#14]
Odd issue found tonight on my community server, for some reason after the mission had been running for hours. Everyone's loadouts had stopped working, people could only select basic gear. Apparently only pilot gear regardless of their team. I don't know if the issue is connected with the TFAR one or because its a Linux server.

**Environment (please complete the following information):**
Version: 
Map (Cam Lao Nam): 

Private dedicated server - Linux

Additional mods:
   
TFAR, CBA, Enhanced Movement

**Comment by Spoffy** [comment]
Closing this out for now as I haven't heard any other reports of this in the last year!
