### ISSUE TITLE
Every 5 seconds FPS drops from 100FPS - 30FPS recovers then repeats

### ISSUE THREAD

**Issue by SovietLobster43** [Savage-Game-Design/Mike-Force#141]
**Describe the bug**
Once I have spawned in the mission and only on this mission every 5 seconds exactly I drop from 100FPS - 30FPS. I'll just be walking around the bases and every 5 seconds the game lags or freezes for 2 seconds and then jumps back up to 100. Repeat the same every 5 seconds.

**To Reproduce**
I tried starting a LAN and hosting a Private Dedicated; in both situations the problem still occurred. 

**Expected behaviour**
I expected that I would start it up as before and I would stay at a more consistent FPS. Arma is Arma and dips hard around lots of units, but I'm standing and walking around base with this happening. 

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: 2.08.149102
Map: Altis Blufor 

* [ ] Official Server
* [ ] Official InDev Server
* [V] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [V] LAN Hosted

Additional mods:
    
Time the bug occurred (Please leave in GMT+0):
3:00pm 

**Additional context**
I had not previously had this issue with Mike Force, but now only these missions are having this issue. I tried The Bra and Cam Lao Nam with still the same result. I have a lower average FPS on those maps, but even then the issue persisted dropping down to 30 FPS every 5 seconds.

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by DanThomas64** [comment]
@SovietLobster43 Are you able to provide a RPT with this issue?
Have you attempted joining to a public server also running the mission to see if you are still getting the dips when you are not also running the server on your machine?

**Comment by SovietLobster43** [comment]
> @SovietLobster43 Are you able to provide a RPT with this issue? Have you attempted joining to a public server also running the mission to see if you are still getting the dips when you are not also running the server on your machine?

I do not have a RPT file, I haven't tried joining public. Mainly because I do not want to.

**Comment by SovietLobster43** [comment]
> @SovietLobster43 Are you able to provide a RPT with this issue? Have you attempted joining to a public server also running the mission to see if you are still getting the dips when you are not also running the server on your machine?

=====================================================================
== C:\Program Files (x86)\Steam\steamapps\common\Arma 3\Arma3_x64.exe
== "C:\Program Files (x86)\Steam\steamapps\common\Arma 3\Arma3_x64.exe" -cpuCount=8 -high -maxMem=8192 -noPause -noSplash -nologs -worlds=empty "-mod=VN;WS;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CBA_A3;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSAFRF;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSUSAF;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CUP Terrains - Core;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@ace;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@Zeus Enhanced;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSGREF;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@RHSSAF;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@CUP Terrains - Maps;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@WMO - Walkable Moving Objects;C:\Program Files (x86)\Steam\steamapps\common\Arma 3\!Workshop\@DCO UnitScanner;C:\Program Files (x86
Original output filename: Arma3Retail_DX11_x64
Exe timestamp: 2022/03/22 03:10:03
Current time:  2022/07/14 18:25:04

Type: Public
Build: Stable
Version: 2.08.149102

Allocator: C:\Program Files (x86)\Steam\steamapps\common\Arma 3\Dll\tbb4malloc_bi_x64.dll [2017.0.0.0] [2017.0.0.0]
PhysMem: 32 GiB, VirtMem : 131072 GiB, AvailPhys : 26 GiB, AvailVirt : 131068 GiB, AvailPage : 29 GiB, PageSize : 4.0 KiB/2.0 MiB/HasLockMemory
=====================================================================

18:25:04 Detected number of DLCs: 20
18:25:04 ---------------------------------------------------------- Game ----------------------------------------------------------
18:25:04                                                                name      appId   owned  installed  available   isDlc
18:25:04                                                              Arma 3     107410     yes        yes        yes      no
18:25:04                                                             Unknown         -1      no         no         no     yes
18:25:04 ---------------------------------------------------------- Dlcs ----------------------------------------------------------
18:25:04  index                                                         name      appId   owned  installed  available   isDlc
18:25:04      0                                                  Arma 3 Maps     249861     yes        yes         no     yes
18:25:04      1                                        Arma 3 Tactical Guide     249862     yes        yes         no     yes
18:25:04      2                                                  Arma 3 Zeus     275700     yes        yes        yes     yes
18:25:04      3                                                 Arma 3 Karts     288520     yes        yes        yes     yes
18:25:04      4                                           Arma 3 Helicopters     304380     yes        yes        yes     yes
18:25:04      5                                          Arma 3 DLC Bundle 1     304400     yes        yes         no     yes
18:25:04      6                                              Arma 3 Marksmen     332350     yes        yes        yes     yes
18:25:04      7                                                  Arma 3 Apex     395180     yes        yes        yes     yes
18:25:04      8                                           Arma 3 Laws of War     571710     yes        yes        yes     yes
18:25:04      9                                                  Arma 3 Jets     601670      no         no        yes     yes
18:25:04     10                                          Arma 3 DLC Bundle 2     612480      no         no         no     yes
18:25:04     11                                                Arma 3 Malden     639600     yes        yes        yes     yes
18:25:04     12                                  Arma 3 Tac-Ops Mission Pack     744950      no         no        yes     yes
18:25:04     13                                                 Arma 3 Tanks     798390      no         no        yes     yes
18:25:04     14                                               Arma 3 Contact    1021790      no         no        yes     yes
18:25:04     15   Arma 3 Creator DLC: Global Mobilization - Cold War Germany    1042220     yes        yes        yes     yes
18:25:04     16                      Arma 3 Creator DLC: S.O.G. Prairie Fire    1227700     yes        yes        yes     yes
18:25:04     17                        Arma 3 Creator DLC: CSLA Iron Curtain    1294440      no         no        yes     yes
18:25:04     18                                            Arma 3 Art of War    1325500     yes        yes        yes     yes
18:25:04     19                           Arma 3 Creator DLC: Western Sahara    1681170     yes        yes        yes     yes
18:25:04 --------------------------------------------------------------------------------------------------------------------------

 I joined a random public server and the issue was not happening, it seems to be only when I host off my computer. I would just play online, but that would kind of defeat the purpose as I don't really like playing online. It would not allow me to send just the file so this is the most recent .rpt since having this issue hope this helps. As a side note I removed all mods I had active and still the issue persisted.

**Comment by Alablm** [comment]
Closing. Mike Force is a multiplayer mission and it sounds like this is a hardware issue stemming from trying to run both the server and client at the same time.
