### ISSUE TITLE
Add master arm type systeam for APCs

### ISSUE THREAD

**Issue by aifinfantrymen** [Savage-Game-Design/Mike-Force#142]
A way to changed the skins on APCs, maybe along the lines of the vehicle arsenal

**Comment by Alablm** [comment]
To be added with https://github.com/Savage-Game-Design/Mike-Force/pull/148, https://github.com/Savage-Game-Design/Mike-Force/pull/149, and https://github.com/Savage-Game-Design/Paradigm/pull/1
