### ISSUE TITLE
Mission Failed on Initial Spawn on Dedicated Official Server

### ISSUE THREAD

**Issue by DatBoiTim** [Savage-Game-Design/Mike-Force#15]
**Describe the bug**
On initial connection, after selecting a slot, you will go through the introductory screen with the billboard, and be spawned into a specific location. Immediately on spawn, you are unable to move, and are greated by the text Mission Failed. After this you are sent through the post mission report and then back to the unit select screen. To my understanding, the mission has not ended and is not ending on when spawned.

**To Reproduce**
Steps to reproduce the bug:
Not sure how to enter the loop but it seems unbreakable. Loop goes as follows

1. Connect
2. Select Unit(Unit seems to be irrelevant, persists regardless of which RTO you pick)
3. Hit OK or Enter
4. Wait for spawn
5. Mission Failed
6. Hit ESC or Continue on GUI of AAR
7. Repeat from step 2

I do know that there was an update to the mission used on the server between disconnecting for the night and reconnecting in the morning (v0.65.02 -> v0.65.03).

**Expected behaviour**
When selecting a Unit and Spawning in I will only recieve the mission failed sequence under the appropriate circumstances.

**Screenshots**

![MKFRC v0-65-03 Mission Failure Despite Mission being active on Spawn](https://user-images.githubusercontent.com/68963748/117557069-56c24d00-b03d-11eb-9e48-fd63b6f00535.png)
This is one of the normal spawn points near what I assume is a duty officer. Note the Intel Sidebar, as well as the squad list.

![MKFRC v0-65-03 AAR Despite Mission Running On Spawn](https://user-images.githubusercontent.com/68963748/117557105-ae60b880-b03d-11eb-8bed-75365d4feea8.png)
What occurs after the 1st image. Leaving this puts you back into unit selection.

**Environment (please complete the following information):**
Version: v0.65.03
Map (specify if Altis Blufor): Cam_Lao_Nam

* [x] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
    
Time the bug occurred (Please leave in GMT+0): ~23:15
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**
Issue persists seemingly regardless of which selectable unit is picked. Issue seems to persist for the user even on disconnect and reconnect, as long as the same server is being connected to.

**Comment by Spoffy** [comment]
I think I know what this issue is! I think it's serverside, thanks for reporting!

**Comment by Ovenmit** [comment]
What was the solution? Were having the same issue.

**Comment by JulianHHS** [comment]
I would like to know how you fixed it?

**Comment by JulianHHS** [comment]
@Ovenmit @Spoffy @DatBoiTim 
I fixed it buy enabling persistant battlefield, changing max player count to 100 AND enabling headless client? I am not sure what that does, I just tried it and now I am not getting the "mission failed" anymore! (BTW, I use TADST to configure my server hope this helps) Player count is a little high now lol, but I am not touching my settings anymore ;) 

Edit: Another thing that might have fixed this issue, is that you have to wait a little while for the server to start-up. So next time you try playing MF on your own server, set it up and the wait 15 - 20 min before playing, this is should fix it.

**Comment by Doctor-Butts** [comment]
I'm looking at the code and this is my best guess:

The player init has code that will end the mission if the server times out trying to initialize, but it's called on the player, so if a player gives the server time to load the mission before connecting, it's less likely to happen.

Persistent battlefield and the mission already running on the server when the player joins is probably how it's not being ended in Julian's case.

**Comment by Loafabreadly** [comment]
> I'm looking at the code and this is my best guess:
> 
> The player init has code that will end the mission if the server times out trying to initialize, but it's called on the player, so if a player gives the server time to load the mission before connecting, it's less likely to happen.
> 
> Persistent battlefield and the mission already running on the server when the player joins is probably how it's not being ended in Julian's case.

+1 this logic is supported by our game servers. We are running persistence & let the server load for 2-3 minutes after players start connecting before pushing through to the map screen.

**Comment by Doctor-Butts** [comment]
Also, per the code, the server has about 30 seconds to confirm it's initialized when the player connects. (assuming I'm reading it correctly)

**Comment by Alablm** [comment]
Closing - Old issue
