### ISSUE TITLE
Normal Voice Chat Problem (no TFAR, no ACRE)

### ISSUE THREAD

**Issue by HoneyButterTheRealOne** [Savage-Game-Design/Mike-Force#16]
Robotic VOIP

When someone is talking in a non TFAR/ACRE server, so using the in game voice chat you are going to hear a very robotic voice, this is the same for every player.

Normal ARMA 3 VOIP is expected

Version: Latest as for 09/05/21
Map (specify if Altis Blufor): Cam Lao 

[x] Official Server
[x] Official InDev Server
[ ] Private dedicated server (i don't know)
[ ] Private dedicated server with Headless client(s) (i don't know)
[ ] LAN Hosted (i don't know)

Additional mods: 
no additional mods

**Comment by Spoffy** [comment]
This is a serverside issue that'll be solved today! :)
