### ISSUE TITLE
Having Issues With Saving Progress (No Persistency)

### ISSUE THREAD

**Issue by Keithchiuth** [Savage-Game-Design/Mike-Force#18]
**Describe the bug**
I have restarted the server 3 times, and each time, progress gets reset.

**To Reproduce**
Standard game, just had to switch a mission file or reset the server.

**Expected behaviour**
Progress to be saved, Zones that were previously captured and FOBs set up would have stayed persistent.

**Screenshots**

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

* [ ] Official Server
* [ ] Official InDev Server
* [X] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:

**Comment by Spoffy** [comment]
Hi Keith, could you provide a .rpt from your session?
The location is in this wiki entry!
https://community.bistudio.com/wiki/Crash_Files

**Comment by Alablm** [comment]
Closing - Duplicate #41
