### ISSUE TITLE
Artillery/AA stuck underwater/in the ground or both

### ISSUE THREAD

**Issue by potatman200** [Savage-Game-Design/Mike-Force#19]
Like the title said, on the island of Phu Quoc, there are some artillery stuck in the ground under the water, and because of them we are stuck and cannot capture said island

![20210509124945_1](https://user-images.githubusercontent.com/83906768/117569494-42766280-b0c6-11eb-822f-878e99c6d916.jpg)

**Comment by Spoffy** [comment]
Phu Quoc is a really buggy zone - I'm thinking of stripping it out for a while in the next release.
Definitely lots of spawning issues though, thanks for reporting these!

**Comment by BrightCandle** [comment]
I have seen a mortar stuck under the ground in a broken building in Saigon zone.
