### ISSUE TITLE
Crashing during mission caching phase on Linux Server

### ISSUE THREAD

**Issue by SyniRon** [Savage-Game-Design/Mike-Force#2]
**Describe the bug**
Mission begins to load and gets halfway through caching mission to client at which point server crashes

**To Reproduce**
Attempt to load mission on Linux Server
(Note: I removed the AH-1G from the mission as it was causing a separate crash. This is a subsequent crash that began occurring after fixing that first crash.)

**Expected behaviour**
Mission starts without crashing

**Screenshots**

**Environment (please complete the following information):**
Version: v0.65.02
Map (specify if Altis Blufor): Cam_Lao_Nam

* [ ] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
TFAR/CBA
Time the bug occurred (Please leave in GMT+0): EST
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 
EST

**Additional context**
I noticed the RPT includes a lot of references to missing semi-colons. I fixed this issue by adding those missing semi-colons. The server started the mission file successfully once the semi-colons were added.

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.
[RPT.log](https://github.com/Savage-Game-Design/Mike-Force/files/6440627/RPT.log)

**Comment by Spoffy** [comment]
This is quite possibly related to the other crashing issue - we're investigating this now, and I'll get back to you when there's a fix!

**Comment by Spoffy** [comment]
Looks like there's a temporary workaround available:
```
Use air_f_vietnam.pbo and vn_structures.pbo from your normal Arma client install, and manually put them on server.
```

**Comment by SyniRon** [comment]
Workaround worked, thanks

**Comment by VyMajoris** [comment]
> Looks like there's a temporary workaround available:
> 
> ```
> Use air_f_vietnam.pbo and vn_structures.pbo from your normal Arma client install, and manually put them on server.
> ```

Do you mean EBOs or PBOs?

**Comment by SyniRon** [comment]
> > Looks like there's a temporary workaround available:
> > ```
> > Use air_f_vietnam.pbo and vn_structures.pbo from your normal Arma client install, and manually put them on server.
> > ```
> 
> Do you mean EBOs or PBOs?

They're ebos currently.

**Comment by ahoys** [comment]
The workaround not working here. The server crashes about immediately after starting the mission (leaving the pool).
The rpt log is filled with ";" -missing errors.

Moved air_f_vietnam.ebo and vn_structures.ebo from Win 10 machine (fresh game install) to the Linux server (arma3/vn/addons/...)

Additional mods:
TFAR, CBA_A3, Actionbuilder

Edit.
Our workaround was to download a modified mission file from another linux server running the mission.

**Comment by Spoffy** [comment]
Hey @ahoys! Sorry to hear it isn't working! Could you post about your issue at https://feedback.bistudio.com/ ? It'll be look at by the core CDLC team then! 

Cheers!
