### ISSUE TITLE
MediKits don't work for reviving people

### ISSUE THREAD

**Issue by Spoffy** [Savage-Game-Design/Mike-Force#20]
**Describe the bug**
Medikits don't work for stabilize and revive currently.

**To Reproduce**
Attempt to revive a downed player as a medic using a medikit.

**Expected behaviour**
The player should be stabilized or revived.

**Environment (please complete the following information):**
Version: 

* [X] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

**Comment by kamiewtype** [comment]
They do work if you have at least 1 first aid kit in your inventory

**Comment by Alablm** [comment]
Closing as this has been fixed
