### ISSUE TITLE
Start players at team select ui with descriptions of teams

### ISSUE THREAD

**Issue by SyniRon** [Savage-Game-Design/Mike-Force#24]
**Is your feature request related to a problem? Please describe.**
Currently players are all automatically placed into Mike Force with no actual guidance of even the existence of the other teams or why they might want to join them. This leads to huge overpopulation of Mike Force and huge underpopulation of other groups especially ACAV.

**Describe the solution you'd like**
Instead of simply dropping players in to a team automatically, spawn them in a spawn zone somewhere hidden while displaying a UI that allows them to choose initial team assignment. This UI could have short descriptions of the teams and their purposes similar to the normal team select now inside the H key folder.

**Describe alternatives you've considered**
Alternatively auto-sort players into the team with the least number of members.

**Comment by aceb20** [comment]
Hey, thanks for posting. Improved player experience is definitely something we're going to touch before Mike Force exits beta including clearer in-game prompts and menus. It's definitely on the roadmap!

**Comment by Alablm** [comment]
Dont plan on implementing the solution suggested here, but the new tutorial should cover the concerns raised.
