### ISSUE TITLE
Headless Client Init Failed

### ISSUE THREAD

**Issue by FieldGeneral1** [Savage-Game-Design/Mike-Force#26]
**Describe the bug**
The headless client connects to the server but gets kicked from the mission during initialization.

Here's the log on the headless client
```
12:38:53 "Paradigm: Initialising player on server"
12:39:08 "Paradigm: Client init timed out waiting for server response."
12:39:21 "hc1/BIS_fnc_log: [BIS_fnc_endMission] Mission failed with 'Broken Init' ending."
```
Here's the log on the server
```
12:38:53 "Paradigm: Initialising player on the server - hc1 - HC9544"
12:38:53 "Paradigm: Aborting player init, as player object is unowned - hc1"
```

**To Reproduce**
Start a headless client to connect to a dedicated server
Start the mission with headless client joined
Headless client has endMission occur on it ~30 seconds after leaving map screen

**Environment (please complete the following information):**
Version: v0.65.03
Map: Cam_Lao_Nam
Windows Server 2019

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [x] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
CBA and TFAR
    
Time the bug occurred: 12:38:53

**Comment by Loafabreadly** [comment]
Interesting that it reports Initializing the HC1 as a player. Could you also include the launch parameters you are using to start up the HC session?

We have two hcs running successfully against a public MF server and didn't run into this issue. Only difference is Windows 2016 iirc.

**Comment by FieldGeneral1** [comment]
-profiles=C:\arma\profiles -client -connect=127.0.0.1 -port=2312 -name=HC1 -mod=vn;@CBA_A3;@TFRB;

**Comment by Loafabreadly** [comment]
@FieldGeneral1 Make sure you are starting the Arma3server.exe, not Arma3. Additionally, are you attempting to run a headless client on the same OS as the Arma 3 Server?

`arma3server.exe -client -connect=xxx.xxx.xxx.xxx -password=yourpass`

**Comment by JDownward** [comment]
Iv had this issue, however the work around I am using is to start the server and mission, connect the HCs then kick them (they should reconnect again automatically) then use #restart via the chat

FYI my servers are hosted by armahosts

**Comment by Alablm** [comment]
Closing as this has been fixed
