### ISSUE TITLE
FOB Persistency 

### ISSUE THREAD

**Issue by Zhickusa** [Savage-Game-Design/Mike-Force#27]
**Describe the bug**
Buildings being unassigned from the HQ building, thus getting no supply even if the HQ has plenty.

**To Reproduce**
I built a small FOB to help our team to push objectives nearby. All the buildings were getting supply because they were assigned to the same supply and none were standalone. Then the server restarted and I drove back to the FOB, but most of the buildings were no longer assigned to the HQ and were standalone for some reason, so they weren't getting supply and started decaying. I checked and the base did have supply after the restart, but wasn't getting to most of the buildings, only the closest ones to the HQ building were getting supply.

**Expected behaviour**
All the buildings to still be assigned to the HQ and getting supply after server restart.

**Environment (please complete the following information):**
Version: 0.65.03
Map (specify if Altis Blufor): 

* [ ] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted
    
Time the bug occurred (Please leave in GMT+0):
9.5.2021 | ~17:00 (7:00 PM)

**Comment by Alablm** [comment]
We're having a similar issue on our server. Base supply values don't appear to be being saved on server shutdown/loaded on restart, resulting in any player made base going abandoned on mission start. This generally results is significant losses to the base itself, occasionally resulting in a complete writeoff if the server hangs when launching forcing a second restart. 
Presently we're using the debug console to teleport the admin to the site then dragging a supply crate to it, however this is obviously not ideal

**Comment by Spoffy** [comment]
This is an odd one, and not one I've noticed before. I'll have an investigate of this. Thanks for reporting!

**Comment by Alablm** [comment]
As a quicker fix that doesn't require a bunch of teleporting around, one of our guys wrote up a script that delivers a large supply crate to all HQs on the map. All you have to do is local execute the following code in the debug console on mission launch. If you're quick you shouldn't lose any of your structures.

`_array = nearestObjects [player, ["Land_vn_hootch_02_03"], 99999];
{
  _isHQ = not isNull (_x getVariable ["para_g_building", objNull]);
  if(_isHQ) then {
    _pos = getPosATL _x;
    createVehicle ["vn_us_komex_small_02",_pos];
    ["resupplybuilding", [_x, "CRATE"]] call para_c_fnc_call_on_server;
  };
} forEach _array;`

**Comment by Alablm** [comment]
Fixed in release 0.66.02
