### ISSUE TITLE
Remove Artillery / AA marker

### ISSUE THREAD

**Issue by enxyo** [Savage-Game-Design/Mike-Force#29]
**Is your feature request related to a problem? Please describe.**
By knowing the exact position to easy to wipe out with out any danger by air or mortar.

**Describe the solution you'd like**
Remove marker from map.

**Describe alternatives you've considered**
None

**Additional context**
For better replayability, in addition to above solution move to a more random/dynamic placement.

**Comment by JDownward** [comment]
PLEASE ^^ this is needed or even have a option to turn it off

**Comment by darkcolouredbox** [comment]
Given how hard it is to find mortar tubes that get hidden in elephant grass, I'd also like the option to have, for example, a 100m wide ellipse marker placed within 100m of the object itself. While it wouldn't give us an exact location of the object we're looking for, it would still give us a narrower search area.

**Comment by Spoffy** [comment]
Thanks for the suggestion! We've got plans to do something similar, although not exactly this. :)

**Comment by Alablm** [comment]
This has been implimented
