### ISSUE TITLE
AH-1G causes server crash on linux

### ISSUE THREAD

**Issue by SyniRon** [Savage-Game-Design/Mike-Force#3]
**Describe the bug**
Attempt to load misison file on linux server results in crash, removing the cobra from the mission fixes this crash

**To Reproduce**
Attempt to load mission on linux server with cobra placed on map

**Expected behaviour**
Server would load without crashing

**Screenshots**

**Environment (please complete the following information):**
Version: v0.65.02
Map (specify if Altis Blufor): Cam_Lao_Nam

* [ ] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
N/A

If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 
EST
**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.
[RPT (2).log](https://github.com/Savage-Game-Design/Mike-Force/files/6440664/RPT.2.log)

**Comment by Spoffy** [comment]
Hey Peak! Had a few reports of this, a known issue with the Linux server build. We're looking into it, and I'll update you as soon as there's a plan to fix it in place!

**Comment by Spoffy** [comment]
Looks like there's a temporary workaround available:
```
Use air_f_vietnam.pbo and vn_structures.pbo from your normal Arma client install, and manually put them on server.
```

**Comment by SyniRon** [comment]
Workaround worked, thanks
