### ISSUE TITLE
Automatic Reporting Abuse

### ISSUE THREAD

**Issue by HoneyButterTheRealOne** [Savage-Game-Design/Mike-Force#33]
**Abusing the automatic radio to flood chat or eject pilots in the current team.**

When a player becomes squad leader the character is going to ask every squad member to regroup causing a massive flood in the chat and once SL you are able to spam regroup orders or dismount, this is very abusable because you can order it one time and sometimes it will eject players from phantoms, or even worse eject the pilot of a full helicopter mid flight, this is more easy to recreate if **the vehicle is damaged.**

I expect nothing to happens since the automatic reporting should be disabled because, let's be real no one actually use it since you can't recruit AI.

Version: Latest as for 10/05/21
Map (specify if Altis Blufor): 

* [x] Official Server
* [x] Official InDev Server
* [x] Private dedicated server
* [x] Private dedicated server with Headless client(s)
* [x] LAN Hosted

Additional mods: no additional mods

At first i thought i made an oopsie and accidentaly ejected from my heli mid flight while transporting a whole squad, then after two other flights, someone sent the dismount order and this time i wasn't ejected but a pilot of an F4 phantom ejected while departing, oh and since every player is far from the current squad leader it automatically sends a regroup order and then you got a flooded chat.

**Comment by Spoffy** [comment]
Thanks for reporting this! I've got a fix in mind :)
