### ISSUE TITLE
Dragged person being stuck when healed

### ISSUE THREAD

**Issue by ashton1cav** [Savage-Game-Design/Mike-Force#34]
**Describe the bug**
If a casualty is healed while being dragged, the downed person will be stuck to the person who is dragging them

**To Reproduce**
Down someone
Have person A drag the downed person
Have person B heal the downed person while still being dragged

**Expected behaviour**
Casualty should be healed and not stuck to whoever is dragging them

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: v0.65.03
Map (specify if Altis Blufor): Cam Lao Nam - Mike Force

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [X] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods: TFAR, CBA
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 
Time: 08/05/2021 & 09/05/2021

**Additional context**
We had this in the original Beta - not sure if it was ever picked up and fixed

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Spoffy** [comment]
Ah, this one - I thought this was all fixed!
This is a CDLC issue rather than Mike Force, so I'll escalate it to the right person.
Thanks for reporting!

**Comment by Alablm** [comment]
CDLC - Closing
