### ISSUE TITLE
RPT entries for vietnam_tet_campaign_commemorative_medal award. 

### ISSUE THREAD

**Issue by DanThomas64** [Savage-Game-Design/Mike-Force#35]
**Describe the bug**
Large amount of RPT entries regarding `vietnam_tet_campaign_commemorative_medal` happening every 15 seconds. 

**To Reproduce**
This seems to be tied to the number of players on the server, but does not directly correlate. 
Started happening as we progressed through the mission, with about 30% of the objectives captured. 

**Expected behaviour**
Unknown if this is by design or not. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5899996/117680617-b6c50a80-b187-11eb-8696-592a4d448ea3.png)

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

* [ ] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods: ACRE2, ACRE2 S.O.G. Prairie Fire Compatibility, CBA
    
Time the bug occurred (Please leave in GMT+0):
Continuous for the past couple of days.

**Additional context**
Unable to upload the RPT due to file size. But can provide.

**Comment by Alablm** [comment]
Fixed in release 0.66.02
