### ISSUE TITLE
Stuck With Green Hornet Gear

### ISSUE THREAD

**Issue by MrOister** [Savage-Game-Design/Mike-Force#36]
**Describe the bug**
After playing CAS shorty i've been stuck with Green hornet vests/gear even after switching to back to Mike Force.
So far we have; restarted the server, tried a different arma profile and killing myself lots of times.

**To Reproduce**
Pick Green hornets
Shut down server
Restart server
Spawn in server for the first time 
"Default mike force spawn"
Have Green hornet gear

**Expected behaviour**
After switching back to mike force have their vests/gear

**Screenshots**
Mike Force chosen under menu "H"
![20210510175333_1](https://user-images.githubusercontent.com/83972003/117689727-59967c80-b1ba-11eb-83db-40b554400093.jpg)

Having Pilot vests and crewman "bulletproof" vests as mike force
![20210510175358_1](https://user-images.githubusercontent.com/83972003/117689860-79c63b80-b1ba-11eb-8f18-d4d6cd7a3eb1.jpg)

**Environment (please complete the following information):**
Version: (BETA 0.65.03)
Map: CAM LAO NAM

* [ ] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
    
![mod list](https://user-images.githubusercontent.com/83972003/117690222-e7726780-b1ba-11eb-98f2-bed9d9c15498.PNG)

Time the bug occurred (Please leave in GMT+0):
19 ish (GMT +0)
Server:
20 ish (GMT +1)

**Additional context**
Not a huge problem just kills immersion

**Thank you for your time and effort!**

**Comment by Doctor-Butts** [comment]
Also encountering this issue on a private dedicated. Does not happen to all players.

**Comment by Spoffy** [comment]
This might be an issue our with arsenal config. I'll take a look. Hopefully it is, as that's easily fixed then.
Thanks for reporting!

**Comment by Spoffy** [comment]
Revisiting this, I'm not sure this is actually a bug - the arsenal is unlocked per-player, and there's no team-specific restrictions on gear right now.
