### ISSUE TITLE
Side tasks

### ISSUE THREAD

**Issue by JDownward** [Savage-Game-Design/Mike-Force#38]
**Is your feature request related to a problem? Please describe.**
Problem being the gameplay is to repetitive.

Go to zone kill VC destroy installations and boom zone delt with

**Describe the solution you'd like**
Have side task to complete.
(I would guess most of these will be spoke force only)
For example a task to extract a downed helicopter crew, must bring them back to one of the camps.
Just something to mix up the repeating procedure. 

**Additional context**
I would guess spike force will have most of them, but acav and Mike force could still have some.

This mission is amazing and I would love to see this last.

**Comment by Spoffy** [comment]
We've got a ton of plans to change things up in our second major update. Thanks for the suggestion - I don't think you'll be disappointed!
