### ISSUE TITLE
Hold Fire Spam

### ISSUE THREAD

**Issue by ashton1cav** [Savage-Game-Design/Mike-Force#39]
**Describe the bug**
It seems if someone drops Napalm and it hits friendlies the whole server gets spammed with a Hold Fire.

**To Reproduce**
Drop napalm somewhere close to friendlies so they get injured by it. Side chat will then spam Hold fire messages and so will AI voices.

**Expected behaviour**
Napalm should injure the friendlies but not cause a loop of hold fire messages.

**Screenshots**
https://drive.google.com/file/d/1qbU-3FUqvGQsBm6AWunYhyGKfTaLaCoE/view?usp=sharing

![image](https://user-images.githubusercontent.com/25756998/117725347-ed794000-b1dc-11eb-9c87-89f0b6006cfc.png)

**Environment (please complete the following information):**
Version: 0.65.03
Map (specify if Altis Blufor): Cam Lao Nam Mike Force

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [X] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:TFAR, CBA
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 
N/A
**Additional context**
N/A

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Spoffy** [comment]
Thanks for reporting @ashton1cav!
This bug is a bit of a pain in the ass, that's defied all attempts to fix it so far. 
Sadly we can't just disable radio (the usual fix) as the artillery system relies on it for voiceovers.

Definitely a frustrating thing to have though, still got an idea or two on how to fix!

**Comment by Alablm** [comment]
I believe this has been fixed
