### ISSUE TITLE
Server not loading player slots

### ISSUE THREAD

**Issue by Iceman5818** [Savage-Game-Design/Mike-Force#4]
**Describe the bug**
I upload the mission to a dedi server, select it, load in and there are no player slots at all. 

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant): As above, all I've done is have my dedicated server switched to SOG, no mods. Uploaded .pbo to mpmissions. Can select from mission select screen, but cannot join any roles. 

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): Standard SOG Map, forget exact name

* [ ] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods: nil

**Comment by Spoffy** [comment]
Hey Iceman, can you confirm for me which version of the mission you're running?

Could you also try just waiting for a bit for me? I've noticed sometimes it can take a minute for the slots to load in. :slightly_smiling_face:

**Comment by Iceman5818** [comment]
I'll double check the mission when I get home but I downloaded it off the
workshop as per your page.

I waited a few mins and still nothing but I can give that another go too.

Cheers

**Comment by Iceman5818** [comment]
Spoffy, added vn to the command line, updated to the new mike force pbo from workshop and it's working, so no more issue! Thank you!
