### ISSUE TITLE
Arsenal issue - no items to take

### ISSUE THREAD

**Issue by failtruk** [Savage-Game-Design/Mike-Force#40]
Describe the bug
If you are in the arsenal and load a loadout you created in another game mode (liberation, antistasi etc) then the next time you use the arsenal you will be restricted to only taking items that are on your current loadout, and nothing else.  If you then remove all you items (in an attempt to fix it :/ ) you will be left unable to take any items from the arsenal.

To Reproduce
- Create Loadout in non Mike Force Game mode and save
- Join Mike Force game
- Got to Arsenal and take load created earlier
- Leave Arsenal
- Open Arsenal
- See issue

Expected behaviour
- Arsenal would be available
- Non MF game mode items would be restricted

Screenshots

**Comment by Alablm** [comment]
@failtruk Were you the logged in admin when this happened?

**Comment by Spoffy** [comment]
If you we're marked as an admin (as alablm asks), then this is an easy fix :)
Thanks for the report! Please do provide that extra bit of info when you get the chance :)

**Comment by failtruk** [comment]
Hi there! I rechecked the issue, and yes it only occurs if you are logged in as an admin.  as an additional note, if you are logged in as an admin and you hit the issue, then you log out of the server and log back in (as a non-admin) the issue persists (limit or no arsenal options).

**Comment by BrightCandle** [comment]
The admin needs to completely disconnect and reconnect to the server to be able to access the arsenal. They can't just logoff and reslot they have to completely connect to the server. A very annoying bug.

**Comment by Alablm** [comment]
Closing - Duplicate https://github.com/Savage-Game-Design/Mike-Force/issues/10
