### ISSUE TITLE
Persistence Being Wiped After Server Restart

### ISSUE THREAD

**Issue by Snakedoct0r** [Savage-Game-Design/Mike-Force#41]
**Describe the bug**
After standard automated server restart, the persistence of the mission is wiped. 

**To Reproduce**
This has happened twice now, both times were after a normal automated server restart on a dedicated server. All mission persistence and player ranks were reset. 

**Expected behaviour**
Mission persistence is not lost.

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: Beta v0.65.03
Map: Cam Lo Nam 

* [ ] Official Server
* [ ] Official InDev Server
* [X] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: Immediately after restart.

**Additional context**
Unsure what is causing this issue but it is a major issue to have. Some guidance or documentation on where the mission saves are stored would be wonderful so server admins can try to manually backup their saves. I assume its either in .vars.armaprofile or vn_mf_latest.cam_lao_nam.pbo as that pbo was created after I started my server up using the mike force mission for the first time.
[arma3server_x64_2021-05-10_10-19-12.zip](https://github.com/Savage-Game-Design/Mike-Force/files/6455123/arma3server_x64_2021-05-10_10-19-12.zip)

**Comment by Spoffy** [comment]
This will be hard to fix, as there's not very much info to go on - we'll be looking into it though
