### ISSUE TITLE
Bridges / Trees category issue in the building system

### ISSUE THREAD

**Issue by Cyborgmatt** [Savage-Game-Design/Mike-Force#42]
**Describe the bug**
The Bridges and Trees categories mistakenly share the same strings leading to issues inside the build menu.

```
      <Key ID="STR_vn_mf_buildingMenu_category_bridges">
        <Original>Bridges</Original>
        <English>Bridges</English>
      </Key>
      <Key ID="STR_vn_mf_buildingMenu_category_trees">
        <Original>Bridges</Original>
        <English>Bridges</English>
      </Key>
```

**To Reproduce**
Open the build menu and select the second Bridges category in the dropdown.

**Screenshots**
![image](https://user-images.githubusercontent.com/3114217/117732290-88771780-b1e7-11eb-971a-addc9a47ea61.png)

**Environment (please complete the following information):**
Version: Beta v0.65.03
Map (specify if Altis Blufor): Cam Lo Nam

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [X] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
N/A

Time the bug occurred (Please leave in GMT+0):
N/A

**Additional context**
N/A

**Comment by Spoffy** [comment]
Nice catch! And a quick fix!

**Comment by Alablm** [comment]
Closing as this has been fixed
