### ISSUE TITLE
buildables.hpp has several lines missing a ';'

### ISSUE THREAD

**Issue by Doctor-Butts** [Savage-Game-Design/Mike-Force#43]
**Describe the bug**
A number of lines in \config\subconfigs\buildables.hpp is missing a semicolon at the end, found in arma 3 rpt file.

There's a lot of lines that are:
name = ""
and not ending in a ;

Version: 
Map (specify if Altis Blufor): 

* [ ] Official Server
* [ ] Official InDev Server
* [X ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [X ] LAN Hosted

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Doctor-Butts** [comment]
Ah, I guess this also ties into the stringtable.xml not being completed.

**Comment by Spoffy** [comment]
Thanks for reporting these! Thankfully these are just warnings, not actual problems, but they need fixing none the lesss!

**Comment by Spoffy** [comment]
This is all fixed on the internal build now :)
