### ISSUE TITLE
Mission not saving progress

### ISSUE THREAD

**Issue by Lumin343** [Savage-Game-Design/Mike-Force#45]
**Describe the bug**
Whenever the mission is changed temporarily to another one on our dedicated server or the server is restarted, we lose all the progress we made in the mission (zones uncaptured, built structures gone, enemy positions back in random places).

**To Reproduce**
Restart the server or reload the mission.

**Expected behaviour**
Progress made in the mission prior to server restart or mission reload to be persisted.

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: v0.65.03
Map (specify if Altis Blufor):  cam lao nam

* [ ] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods: Task Force Radio, CBA3
    
Time the bug occurred (Please leave in GMT+0): European time zone (GMT+1)
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**
The sever **does not crash** and there are no error files generated.

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Spoffy** [comment]
Thanks for the report - we've had similar issues reported on occasaion, we'll investigate this!

**Comment by Alablm** [comment]
Closing - Duplicate https://github.com/Savage-Game-Design/Mike-Force/issues/41
