### ISSUE TITLE
F-4C Phantom Co-pilot can not leave vehicle (except by ejection)

### ISSUE THREAD

**Issue by Zardukah** [Savage-Game-Design/Mike-Force#46]
**Describe the bug**
When a player enters the F4C Phantom 2 person jet as a co-pilot/bomber they cannot exit the vehicle except by ejection. The ejection renders the vehicle destroyed. 'Get out' option is absent in the scroll menu.

**To Reproduce**
Have a pilot get into the vehicle, then have a copilot get into the vehicle. At this point the copilot will never be able to exit, even when the pilot exits first.

**Expected behaviour**
'Get out' option should be present for copilot

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: 
N/A

* [x] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
None

**Comment by Alablm** [comment]
This seems to be a bug with the CDLC, and as such should be reported in accordance with this forum post https://community.sogpf.com/threads/44-Bug-reporting
