### ISSUE TITLE
Building zone restriction

### ISSUE THREAD

**Issue by sapien82** [Savage-Game-Design/Mike-Force#48]
Players arent visibly warned of the restriction of building inside the main 4 FOB's using the buildng requirements menu on the right hand panel

Load arma3 launch mike force , set up as a engineer and open the build menu , select any item to build and attempt to build in the FOB. Notice that the requirements on the right no longer shows as restricted in the main 4 FOB's
but the building ghost item is red.

**Comment by Alablm** [comment]
Closing as this has been fixed
