### ISSUE TITLE
Arsenal Missing Ammo

### ISSUE THREAD

**Issue by JasperRab** [Savage-Game-Design/Mike-Force#5]
**Describe the bug**
Ammo for different guns are locked by rank even tough the weapon isn't. This causes issues with saving loadouts.

**To Reproduce**
You can pick up an M16 for example, and then get some ammo. Save this as a preset, and then try and load it.
It will show up with an error that the ammo type is missing.

**Expected behaviour**
Ammo for guns that are available should also be available.

**Environment (please complete the following information):**
Version: 0.65.02

* [ ] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

**Comment by JDownward** [comment]
You can get around this by deselecting your weapon then reselect the weapon and the primary ammo will use able again

**Comment by Spoffy** [comment]
Thanks for posting the workaround JDownward! I'll look at the arsenal config and see if this can be sorted.

**Comment by Spoffy** [comment]
Thanks for the bug, this has been confirmed and will be fixed in a future release!

**Comment by joar** [comment]
Some of the weapons and ammo types affected:
```hpp
			{"vn_m1carbine",{0,0,0,0}},
			{"vn_m2carbine",{1,1,1,1}},
			{"vn_carbine_15_mag",{5,4,4,5}},

			{"vn_m14",{-1,1,3,-1}},
			{"vn_m14_10_mag",{-1,5,3,-1}},

			{"vn_m16",{-1,0,0,-1}},
			{"vn_m16_20_mag",{-1,6,6,-1}},

			{"vn_m60",{-1,0,0,-1}},
			{"vn_m60_100_mag",{-1,3,3,-1}},

			{"vn_m45",{-1,3,3,-1}},
			{"vn_m45_mag",{-1,5,6,-1}},

			{"vn_m40a1",{-1,3,-1,-1}},
			{"vn_m40a1_mag",{-1,4,-1,-1}},

			{"vn_mc10",{-1,4,4,-1}},
			{"vn_mc10_mag",{-1,5,6,-1}},
```

**Comment by Alablm** [comment]
This has been fixed in the current release, closing.
