### ISSUE TITLE
Map markers on player built FOB's

### ISSUE THREAD

**Issue by bradleyoosterveen** [Savage-Game-Design/Mike-Force#50]
**Is your feature request related to a problem? Please describe.**
When I build an FOB, I either have to mark it on the map myself or memorize the position. Player placed map markers will always be removed through one way or another, which can cause problems like forgetting where the FOB is placed.

**Describe the solution you'd like**
Show a map marker on the position of a player build FOB.

**Describe alternatives you've considered**
Placing a map marker yourself, but as said above this marker marker will eventually be removed one way or another.

**Additional context**
None

**Comment by darkcolouredbox** [comment]
Player-constructed FOBs are already assigned a unique name once a Situation Room has been constructed. I haven't looked at the code associated with creating objects, but I can't imagine it would be hard to use that unique name and Situation Room position to create a marker that is removed when the FOB runs out of supplies.

**Comment by Alablm** [comment]
This has been implemented in the latest internal version of Mike Force

**Comment by Alablm** [comment]
Fixed in release 0.66.02
