### ISSUE TITLE
Limitation of people in ACAV and Green Hornets

### ISSUE THREAD

**Issue by ashton1cav** [Savage-Game-Design/Mike-Force#52]
**Is your feature request related to a problem? Please describe.**
Okay so, big server + alot of people in the air = disaster. 

We have a dedicated ATC guy who has taken the role like a champ!

**Describe the solution you'd like**
I would like to see some form of solution to limiting the amount of people that can be in the Green Hornets and ACAV for that matter. Maybe when it reaches a certain amount of members it stops allowing new members until there is space? Something along them lines.

**Describe alternatives you've considered**
We have enforced TFAR on pilots to try and atleast get them on comms and limit people without TFAR from flying.. its a catch 22 at the moment as its quite difficult to admin that.

**Additional context**
N/A

**Comment by Saarine-E** [comment]
I'm also seeing people use ACAV as normal infantry instead of Mike, because it lets them build things and use more ground vehicles without any drawbacks.

**Comment by Spoffy** [comment]
Agreed - this is an option we want to make available to people!

**Comment by Alablm** [comment]
This has been implemented in the latest internal version of Mike Force.

**Comment by Alablm** [comment]
Fixed in release 0.66.02
