### ISSUE TITLE
RPT Spam - String @STR_para_overlay_buildable_description not found

### ISSUE THREAD

**Issue by ashton1cav** [Savage-Game-Design/Mike-Force#54]
**Describe the bug**
Server RPT is spammed with String @STR_para_overlay_buildable_description not found

**To Reproduce**
Boot Mike Force, give it a few minutes and see the lines appear in RPT

**Expected behaviour**
Guessing its just missing from the stringtable

**Screenshots**

**Environment (please complete the following information):**
Version: Latest MF
Map (specify if Altis Blufor): Cao Lao Nam

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [X ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:TFAR, CBA
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by AstralEUD** [comment]
To addition, There is two bugs in stringtables.

`      <Key ID="STR_vn_mf_buildables_require_vehicles">
        <Original>==== Resupply buildings require vehicles ====</Original>
        <English>==== Resupply buildings require vehicles ====</Original>
      </Key>`

This must be changed into

`      <Key ID="STR_vn_mf_buildables_require_vehicles">
        <Original>==== Resupply buildings require vehicles ====</Original>
        <English>==== Resupply buildings require vehicles ====</English>
      </Key>`

and,

**STR_vn_mf_param_enable_ranks** has duplicated.

**Comment by Alablm** [comment]
Closing as this has been fixed
