### ISSUE TITLE
In mission fonts are too small

### ISSUE THREAD

**Issue by RoyDodd** [Savage-Game-Design/Mike-Force#6]
The text font in mission windows is a little hard to read. This includes the messages on mission start. I run at 1920x1080 and my Video>Display>Layout Size is Small.

Here is an example from the keybindings window. The button text is fine but the keys are too small.

![107410_20210507120725_1](https://user-images.githubusercontent.com/7331059/117485904-8f273580-af2e-11eb-9308-afcc8d87c4f1.png)

**Comment by Spoffy** [comment]
Definitely agree, this'll be looked at!

**Comment by Doctor-Butts** [comment]
This happens with a lot of the mission specific UI: It looks fine when the Interface size is 'normal' but when it is set to 'small' it is hardly legible.

Attaching more examples on a fullscreen window view- resolution is 1440x900:
![image](https://user-images.githubusercontent.com/22239077/117734771-23f59180-b1c2-11eb-9c1a-4d6be62288ee.png)

![image](https://user-images.githubusercontent.com/22239077/117734887-615a1f00-b1c2-11eb-9036-6e02f8784f9b.png)

![image](https://user-images.githubusercontent.com/22239077/117735000-a0887000-b1c2-11eb-8a2a-04d6bba28a69.png)

![image](https://user-images.githubusercontent.com/22239077/117735369-518f0a80-b1c3-11eb-927e-c22c3dea401c.png)

![image](https://user-images.githubusercontent.com/22239077/117735452-75eae700-b1c3-11eb-9276-0aa1eb740d1c.png)

**Comment by Spoffy** [comment]
Thanks for the report! This is an issue with our font config within the CDLC, and will most likely be fixed alongside that. This ticket will be closed as there's nothing to do within the mission itself for now!
