### ISSUE TITLE
Segmentation fault on linux dedicated server

### ISSUE THREAD

**Issue by ArtyomFR** [Savage-Game-Design/Mike-Force#60]
**Describe the bug**
Hi, when starting the mission with or without mods, we get a segmentation fault (core dumped) error and the server crash.
We do not have any error in vanilla ArmA, ArmA + Mods.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
1. Start server.
2. Connect.
3. Try launching Mike Force.
4. Server Crash (Core Dumped).

**Expected behaviour**
1. Start server
2. Connect
3. Try launching Mike Force
4. Arrive on slot selection screen.

**Environment (please complete the following information):**
Version: Arma 3 Console version 2.04.147540 x64 : port 2402
Map (specify if Altis Blufor): Cam Lao Nam

* [ ] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
Test in Vanilla and :
- CBA_A3
- ACRE2
- ACRE2_SYS_SOG
    
**Dedicated server RPT**
[LOG_MIKE_FORCE.txt](https://github.com/Savage-Game-Design/Mike-Force/files/6468390/LOG_MIKE_FORCE.txt)

**Comment by Zylon** [comment]
Exact same issue here as described above.
Server runs fine with, and without mods. `-mod=vn` works fine too without crashing.
Server also doesn't crash at boot. It starts spewing errors when the mission is selected and loaded, and then crashes.

Same **version**: Arma 3 Console version 2.04.147540 x86 : port 2302
Same **map**: Cam Lao Nam
Also just a private dedicated server for friends.
**Linux kernel**: 5.4.0-65-generic
**Distro**: Ubuntu 20.04.2 LTS

I hope this extra case helps.

**Comment by ArtyomFR** [comment]
Duplicate and workaround in #2
