### ISSUE TITLE
ACRE Support

### ISSUE THREAD

**Issue by ColinM9991** [Savage-Game-Design/Mike-Force#61]
**Is your feature request related to a problem? Please describe.**
Currently this mission only supports Task Force Radio as it contains an Arsenal whitelist which filters out all ACRE radios. It would be nice to use ACRE with this mission as not all communities will be using TFAR.

**Describe the solution you'd like**
The ability to select ACRE radios from the Arsenal Misc page as ACRE prevents players from using the URC-10

**Comment by CH-Potter** [comment]
As a possible workaround for now you can use Zeus (need to be logged in as admin on a DS) and drop in a few PRC-77's.

**Comment by Spoffy** [comment]
Shouldn't be too hard - bit of a low priority to sort this though, as communities are free to mod the mission themselves to fix this issue!

**Comment by ColinM9991** [comment]
@Spoffy are you sure? The readme still says the following

`please do not modify, derive new works or republish it`

**Comment by Spoffy** [comment]
We relaxed the policy a little after release @ColinM9991! https://community.sogpf.com/threads/258-Modifying-Mike-Force

**Comment by Alablm** [comment]
Acre Support is included in the current dev build of Mike Force

**Comment by Alablm** [comment]
Fixed in release 0.66.02
