### ISSUE TITLE
Headless clients disconnect on joining

### ISSUE THREAD

**Issue by Spoffy** [Savage-Game-Design/Mike-Force#64]
Cause:
 1:15:37 "Paradigm: Initialising player on the server - hc1 - HC7196"
 1:15:37 "Paradigm: Aborting player init, as player object is unowned - hc1"

(This is not a good example of a bug report, and is being used to track issues internally. Please use the template provided!)

**Comment by JDownward** [comment]
For now I have found a solution, kick the headless clients then use the #restart to get the headless client to stay connected

**Comment by Alablm** [comment]
Closing as this has been fixed
