### ISSUE TITLE
View Distance (Problem but Not a Bug)

### ISSUE THREAD

**Issue by SonofKylesMom** [Savage-Game-Design/Mike-Force#66]
Love the mod.  Have already logged many hours.

That said, the 5km view distance makes it rather difficult to perform CAS and ISR with jets like the F-4.  Normally I operate with 8km+ just because I am usually already flying at 2km altitude to protect myself from ground fire like AA & AAA.

**Comment by EpiicPenguin** [comment]
it would be helpfull to have septrete object and terrain viewdistence settings and the ability to turn off the auto viewdistence limiter that activates when your fps drops. 
its a great feature for most people but my pc (a 2017 amd fx 8 core, which runs everything except arma great.) i just live at 20fps on multiplayer servers most of the time no matter what the viewdistence is set to. i fly helis and jets all the time at 20 fps and im really good at it but on MF my 20fps triggers the viewdistence to drop down to 500m. its a great feature we just need the ability to turn it off in certain circumstances.

**Comment by Alablm** [comment]
Closing as view distance settings have been expanded
