### ISSUE TITLE
Supply boxes were destroyed before player enter the area. Task cannot be done.

### ISSUE THREAD

**Issue by Encall** [Savage-Game-Design/Mike-Force#67]
**Describe the bug**
Supply boxes at HQ were destroyed and sunk underground even before player enter the area. Which cause the task "Destroy Site" cannot be done. Sometimes 2 of supply boxes were destroyed and there's only one left.

**To Reproduce**
No Idea

**Expected behaviour**
All of 3 supply boxes should be on ground and not be destroy beforehand.

**Screenshots**

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

* [ ] Official Server
* [ ] Official InDev Server
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Spoffy** [comment]
There's not enough information here to fix this - but we'll keep an eye out for it in case it pops up again, in which case we'll sort it!
