### ISSUE TITLE
white phosphorus in radio CAS

### ISSUE THREAD

**Issue by MrPyroPT** [Savage-Game-Design/Mike-Force#68]
**Is your feature request related to a problem? Please describe.**
The lack of white phosphorus on the CAS department is a bbit of a nonsense, since it was used immensely in vietnam, and would better the experience when its dark, since the flares last for a short time

**Describe the solution you'd like**
Maybe add WP to one of the existent CAS options

**Comment by MrPyroPT** [comment]
Also, having ETA on the fire missions would be helpful, and would prevent a lot of friendly fire incidents

**Comment by Spoffy** [comment]
You should be able to change to a white phospherous loadout in the master arm menu, and I'm pretty certain there are artillery call-ins from the radio menu that have white phosphorus! Are you specifically talking about the CAS in the radio support menu here?
