### ISSUE TITLE
Rank and Unlocks randomly getting reseted.

### ISSUE THREAD

**Issue by MrPyroPT** [Savage-Game-Design/Mike-Force#69]
**Describe the bug**
well, if experienced this a couple of times. yesterday i got 3 resets randomly. 

 ***the mission didnt restart, it just randomly resets***

**To Reproduce**
sometimes happens when servers restart.

**Comment by Dave4291** [comment]
Duplicate of #11

**Comment by Alablm** [comment]
Closing - Duplicate #11
