### ISSUE TITLE
Parameter for blue force tracker

### ISSUE THREAD

**Issue by blasqwerty** [Savage-Game-Design/Mike-Force#7]
**Is your feature request related to a problem? Please describe.**
Since BFT wasn't a thing during the war, having the option to disable it would be welcomed.

**Describe the solution you'd like**
In the parameters options in the lobby, add a param for player trackers on map. I understand that some players prefer to see each other on map.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Spoffy** [comment]
Happy to add a param for this!

**Comment by Spoffy** [comment]
Thanks for the suggestion, this has been confirmed and will be added in a future release, if possible!

**Comment by Alablm** [comment]
This has been implemented in the latest internal version of Mike Force.

**Comment by Alablm** [comment]
Fixed in release 0.66.02
