### ISSUE TITLE
Master Rearm unavailable after Respawn

### ISSUE THREAD

**Issue by Bastimoo** [Savage-Game-Design/Mike-Force#70]
**Describe the bug**
Master Rearm on Helicopters and Jets is unavailable (does not show up in the mouse-scroll-wheel-menu after I respawn.
Green Hornet is selected as a role, vehicle is on the appropriate platform/location. Master rearm does show up when I first join the server.

**To Reproduce**
Die, respawn at the airbase (as Green Hornet), jump in a vehicle of choice and try to find master rearm.

**Expected behaviour**
Master rearm should be available in the mouse-scroll-wheel-menu.

**Screenshots**
-

**Environment (please complete the following information):**
Version: 0.65.03
CAM LAO NAM

* [X] Official Server
* [ ] Official InDev Server
* [X] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
None.

Time the bug occurred (Please leave in GMT+0): 16:00, 14th of may
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**
-

**Comment by Alablm** [comment]
Stale and cant repro
