### ISSUE TITLE
No radio support on dedicated server

### ISSUE THREAD

**Issue by DoktorMahn** [Savage-Game-Design/Mike-Force#71]
**Describe the bug**
When running the mission on a dedicated server, I can not utilize the built in support system. Even with radio operator training and an RTO backpack, the screen is blank when trying to call in support. I've tried changing teams and logging in/out of admin mode. I do not have this problem locally hosting without a dedicated server. 

**To Reproduce**
Run the mission on a dedicated server. Go to the arsenal and get an RTO backpack. Go to the duty officer and receive RTO training. Try to call in air or artillery support. The screen will be blank. 

**Expected behaviour**
I would expect the support module to work on a dedicated server, when I have RTO training and and an RTO backpack. 

**Environment (please complete the following information):**
Version: 
Map (Cam Lao Nam, Blufor, Mike Force mission): 

* [ ] Official Server
* [ ] Official InDev Server
* [X ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods: None

**Additional context**
I find it extremely odd that I do not have this issue when locally hosting without a dedicated server. 
![20210514095037_1](https://user-images.githubusercontent.com/83934465/118304577-b2586480-b49b-11eb-996b-42d9fdb8213e.jpg)

**Comment by JDownward** [comment]
whats your rank on the server ??

**Comment by Koch** [comment]
Out of interest: are you on Linux?

**Comment by DoktorMahn** [comment]
@Koch No I am not on Linux

@JDownward I'm not entirely sure, all I know is that a friend of mine who joined the server could do it just fine(call in support), and he's played less on the server than me. I can't imagine it has anything to do with rank, since I turned that off in parameters.

**Comment by JDownward** [comment]
hmm the only time iv ever had issues with it was because i was a private

**Comment by Alablm** [comment]
CDLC issue in all likelihood
