### ISSUE TITLE
Smoke from M60 smoke 105mm round causes player damage

### ISSUE THREAD

**Issue by Nich10solo** [Savage-Game-Design/Mike-Force#72]
The smoke from the M60 smoke round from the 105mm Howitzer does damage to players. My players have noted the smoke is yellow, similar to the chemical gas. 

Footage from the artillery side: https://youtu.be/76UVzLr1KKU

**Comment by Dave4291** [comment]
It might help if it was labelled as such, but the M60 105mm smoke round uses white phosphorous. The damage effect is almost certainly intentional.

**Comment by Nich10solo** [comment]
Hmm. So then I assume the separate white phosphorus ammo type is more for incendiary purposes?

**Comment by Alablm** [comment]
This github is in relation to the Mike Force game mode, not the S.O.G. Prarie Fire DLC. As the howitzers are not included in Mike Force, you'll have to direct your issue elsewhere, namely https://community.sogpf.com/threads/44-Bug-reporting

**Comment by Spoffy** [comment]
This should be sorted!
