### ISSUE TITLE
Anybody can use Cayuse helo's

### ISSUE THREAD

**Issue by ashton1cav** [Savage-Game-Design/Mike-Force#74]
**Describe the bug**
Anybody can use Cayuse helo's

**To Reproduce**
Go upto a Cayuse as any unit and you can get in the pilot seat

**Expected behaviour**
Only Green Hornets should be able to fly them.

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: Latest MF 
Map (specify if Altis Blufor): Cao Lao Nam 

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [X] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:TFAR, CBA_A3
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by ashton1cav** [comment]
Weirdly enough.. after a server restart I cant reproduce this. Mission.sqm looks fine, helo's are synced to the correct logic and have the init set. Will continue to look into it.

**Comment by Alablm** [comment]
The Cayuses north of the green hornets spawn area are intentionally left open to accommodate low player counts. If you want to lock them down you'll have to edit the vehicle's init.

**Comment by Des8559** [comment]
Is that official because if it is why put ground vehicles in at all?

**Comment by Spoffy** [comment]
This is a very deliberate choice - the cayuse helicopters are slow, and relatively useless compared to their heavier counterparts. 
This is to enable players to get into the AO when the playercount is low. 

That said, it might be something we revisit in the future when we rebalance the air assets in the gamemode.
