### ISSUE TITLE
Cant capture leghhorn

### ISSUE THREAD

**Issue by PepeUltimate** [Savage-Game-Design/Mike-Force#75]
**Describe the bug**
Leghhorn was the last AO on the mission and we could not capture, restarted the mission started with Leghhorn and could not capture

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant): try to capture it.

**Expected behaviour**
A clear and concise description of what you expected to happen. we expected to capture it to win.

**Screenshots**

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor):  Vanilla Mike Force

* [ ] Official Server
* [ ] Official InDev Server
* [ X] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods: we were running vanilla no mods
    
Time the bug occurred (Please leave in GMT+0): 1 AM CST
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred. i do not have access to the RPT so i cannot provide it.

Leaving this here just in case other people are having the issue

**Comment by Alablm** [comment]
https://github.com/Savage-Game-Design/Mike-Force/issues/56

Search function is your friend

**Comment by Alablm** [comment]
Closing as duplicate/resolved
