### ISSUE TITLE
If last man in an AO is wounded, all AI despawn

### ISSUE THREAD

**Issue by Dave4291** [Savage-Game-Design/Mike-Force#76]
**Describe the bug**
All AI despawn (intentionally, I assume) if there are no players in an active area. But if the last player is wounded, all AI will still despawn. If they are then able to crawl, new AI will immediately be spawned. This is obviously somewhat confusing for the person who's down.

**To Reproduce**
Have one person in an AO who gets wounded. Watch in spectate mode what happens to the AI.

**Expected behaviour**
A player being wounded should not count as them not being present at all for the purposes of AI despawning.

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: 0.65.03

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [*] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
    
Time the bug occurred (Please leave in GMT+0):
19:45 BST 16/05/2021

**Additional context**
N/A

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.
I'm assuming the .RPT is not relevant here.

**Comment by darkcolouredbox** [comment]
Likely an issue with AOs checking for the presence of BLUFOR, but downed players being considered CIVILIAN to prevent AI from engaging them.

**Comment by Kexanone** [comment]
It actually also does happen when you are not the last man in the AO. I believe it's also a proximity check. We had a garrisoned FOB in the AO and I went on recovering a wreck alone, got wounded and the AI also despawned next to me.

**Comment by Alablm** [comment]
Fixed with https://github.com/Savage-Game-Design/Paradigm/pull/2
