### ISSUE TITLE
All AI in a zone aggro at once, leading to an empty zone after an initial gunfight

### ISSUE THREAD

**Issue by Saarine-E** [Savage-Game-Design/Mike-Force#77]
**Is your feature request related to a problem? Please describe.**
On first contact, most if not all of the AI inside the zone aggros on players. This leads to a very intense gunfight lasting about 10-20 minutes, after which things slow down. For the rest of the zone there's very little resistance (or none at all), usually even including decrewed AA and mortar pieces. Understandably this is very boring for the rest of the zone clearing, because it only consists of running from one site to another and blowing them up, encountering maybe 1-2 AI per site or none at all.

**Describe the solution you'd like**
Make enemies spawn from a tunnel entrance on the HQ when players aren't close to it (maybe 3-400 meters away at minimum) and add it to the objects that need to be destroyed for the HQ to be neutralized. The spawning enemies should head towards the outlying sites, prioritizing the weakest ones. The tunnel could possibly even be made enterable with randomized enemies which would necessitate players clearing it first.

**Describe alternatives you've considered**
- Make reinforcements spawn from outside the zone and head toward the HQ or players.
**OR**
- Reduce the range at which AI aggro on players, which will make the initial gunfight a lot smaller but will draw out the overall fight.

**Comment by Spoffy** [comment]
We've got plans to fix this in one of our upcoming updates! :) Not quite the way you suggest though - you'll have to wait and see! :)

**Comment by Alablm** [comment]
Fixed with release 00.66.03, closing
