### ISSUE TITLE
Add an Object Initialisation file for vehicle/crate customisation

### ISSUE THREAD

**Issue by I-MK84-I** [Savage-Game-Design/Mike-Force#79]
**Is your feature request related to a problem? Please describe.**
Currently vehicles/crates spawn with either the default or fixed items in their cargo. 

**Describe the solution you'd like**
Have an ObjectsInit file that allows server admins to customise vehicle/crates when they spawn/respawn in game. Example for this is in the KP Liberation game mode and their use of kp_objectInits.sqf file.
https://github.com/KillahPotatoes/KP-Liberation/wiki/EN_ConfigFiles

**Comment by Alablm** [comment]
Closing as crates now have a config file
