### ISSUE TITLE
Mission End state and auto wipe

### ISSUE THREAD

**Issue by JDownward** [Savage-Game-Design/Mike-Force#80]
**Is your feature request related to a problem? Please describe.**
there is no mission end state (mission success screen) when all zones are captured. this can cause issues for the server admins

**Describe the solution you'd like**
add a trigger when all zones are captured = mission success and once that is done it auto wipes the mission file 

**Describe alternatives you've considered**
cannot think of any at the moment

**Additional context**

**Comment by Alablm** [comment]
Fixed in release 0.66.02
