### ISSUE TITLE
Checkpoints as fast travel, not respawn points

### ISSUE THREAD

**Issue by bradleyoosterveen** [Savage-Game-Design/Mike-Force#81]
**Is your feature request related to a problem? Please describe.**
Currently, players can respawn on checkpoints. This can create multiple problems:
- Since players spawn with the stuff they had when they died, they need some form of resupply. One way of doing that is by having logistics bringing fresh crates over to the checkpoint. After a while, this can create more "trash" on the map. Another way is to get the ammo from the arsenal and fill up a box that way, but no player wants to do that for as long as the checkpoint is being used.
- To get around the previous, players can spawn at an FOB, reload their loadout, then hit the respawn button and respawn at the checkpoint. I'm guessing that this play style is not intended.

**Describe the solution you'd like**
Allow players to fast travel to a checkpoint. Disable respawn on checkpoints.

**Alternatives**
Saving your current loadout as a respawn loadout.

**Comment by Kexanone** [comment]
The current way gives a good balance for the Green Hornets. When the FOB has been established, troop transport is rarely required, but they can then switch to resupply runs. Ammo supplies, _etc._ would become obsolete otherwise.

**Comment by Spoffy** [comment]
Fast travel won't be added (except possibly as a low-pop feature) as it undermines green hornets gameplay. There's definitely some more balancing needing around resupply and making FOBs full-fledged bases, but I don't think fast travel is the solution to this one! 🙂
