### ISSUE TITLE
Disable "Viewdistance" feature.

### ISSUE THREAD

**Issue by grappas** [Savage-Game-Design/Mike-Force#82]
**Is your feature request related to a problem? Please describe.**
I'm using my own mods modifying Viewdistance, but Mike Force's Viewdistance script works in a loop, conflicting with mine mods.

**Describe the solution you'd like**
Is there any chance to add under "Gamemode Options" possibility to disable "Viewdistance" setting?

**Comment by Spoffy** [comment]
Planned for the next release :)

**Comment by Alablm** [comment]
Closing as a toggle has been added
