### ISSUE TITLE
Hide OPFOR marker parameter

### ISSUE THREAD

**Issue by warzen** [Savage-Game-Design/Mike-Force#83]
**Is your feature request related to a problem? Please describe.**
Right now, it's super easy to wipe all Artillery and AA sites just by being RTO and using AI support modules. Just spam until everything is dead.

**Describe the solution you'd like**
It would be nice to add a mission starting parameter to hide all OPFOR markers so that infantry need to go to the ground and locate where those sites are.
Why a mission parameter: because it's totally understandable that some players/teams want to not chase each site for ages.
"Hide OPFOR marker": no (default)/yes

**Describe alternatives you've considered**
Increase the error margin between the real site and the map marker. It could be a good alternative solution. Both could be implemented. This would need an additionnal paramater:
"OPFOR marker margin of error": 20m (default)/50m/100m/200m/500m

**Additional context**
No.

**Comment by Spoffy** [comment]
We've got some cool plans to handle OPFOR markers - unfortunately we can't just take away the markers or increase distances. We tried it during testing, and nobody wants to spend 20 minutes running around looking for a mortar hidden in a bush! 😆
