### ISSUE TITLE
Any Faction can fly from Co-Pilot seat

### ISSUE THREAD

**Issue by Johno-ZA** [Savage-Game-Design/Mike-Force#84]
**Describe the bug**
Any faction can climb into Co-Pilot and take controls and fly aircraft

**To Reproduce**
- Choose a faction besides Green Hornets
- Climb into Co-Pilot Seat
- Select "Take Controls" from the scroll menu
- Take Off

**Expected behaviour**
Should kick ACAV, Mike Force or Spike Team from Pilot or Co-Pilot seats.

**Screenshots**
Not Needed

**Environment (please complete the following information):**
Version: v0.65.03
Map (specify if Altis Blufor): Cam Lao Nam

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [X] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
TFAR, CBA. JSRS SOUNDMOD, Blastcore Standalone Version, Enhanced Movement
    
Time the bug occurred (Please leave in GMT+0):
N/A

**Additional context**
N/A

**Comment by Alablm** [comment]
Closing as this has been fixed
