### ISSUE TITLE
Bug/feedback: Hitbox on Resupply crate is extremely off

### ISSUE THREAD

**Issue by ShoppyCodes** [Savage-Game-Design/Mike-Force#87]
**Describe the bug**
The buildable resupply boxes are incredibly difficult to use due to the hitbox being far away from the actual building itself. The screenshot shows how far away the hitbox for re-supply is, however looking at the ammo resupply does not give the scroll-wheel option.

**To Reproduce**
Build ammo resupply box
Use up ammo in heli
Land next to it
Look at the resupply box to re-arm - the scroll-wheel option doesn't appear.

**Expected behaviour**
Look at box, get scroll-wheel option to resupply

**Screenshots**
![image](https://user-images.githubusercontent.com/26325324/118804487-a9510400-b89c-11eb-9127-42a30c4c294a.png)

**Environment (please complete the following information):**
Version: Beta v0.65.03
Map (specify if Altis Blufor): Cam Lao Nam

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [X] LAN Hosted

Additional mods: Zeus Enhanced (used to help test, doubt it will have any impact)

**Additional context**
Strangely, it seems a lot easier to do this in third-person, but in first-person it's waaaay off.

**Comment by Alablm** [comment]
There might be a way to lower the interaction location with sqf, however, the crux of the issue lies within the CDLC itself, and as such it should be reported on the feedback tracker IAW https://community.sogpf.com/threads/44-Bug-reporting

**Comment by ShoppyCodes** [comment]
Apologies, I will report it there - thanks!

Edit: For anyone who might want to see it: https://feedback.bistudio.com/T158678

**Comment by Spoffy** [comment]
Should be all fixed!
