### ISSUE TITLE
Player 1st person view goes black after entering vehicle which has re-Lock timer timing out during animation

### ISSUE THREAD

**Issue by RG-Sneaker** [Savage-Game-Design/Mike-Force#88]
**Describe the bug**
Player 1st person view goes black after entering vehicle which has re-Lock timer timing out during "enter vehicle" animation
Vehicle re-Lock timer should be stopped at the **"Player enter" event** instead of being able to time out while the Player is experiencing the "entering" animation.

**To Reproduce**
Enter a vehicle when it is about to re-Lock

**Expected behaviour**
If "Enter" action is allowed by the vehicle, the player expects the vehicle not to lock while entering.

* [X] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Server Name: [22A] VIETNAM LIBERATION | UK/EU | Discord.gg/Wg7HsVqG4Z 
IP & Port: 194.147.121.132:2302
Location: GB [Europe]
Quality: 32 ms
Activity: 8/35
Password Protection: Disabled
BattlEye Protection: Enabled
Last Joined: 0 days (May 18, 2021, 3:29 AM)
Mission Name: Mike Force (Beta v0.65.03)
Game Mode: MIKEFRC
Terrain: Cam_Lao_Nam
Status: PLAYING
Server Difficulty: Regular
AI Difficulty: Normal
Third Person View: Enabled
Crosshair: Enabled
Advanced Flight Model: Disabled
Server OS: Windows, Dedicated
Server Version: 2.04.147540

**Comment by Alablm** [comment]
A fix for this has been implemented in the latest internal version of Mike Force.

**Comment by RG-Sneaker** [comment]
Aren't you supposed to note which version for traceability ? Which release version is this planned for?

**Comment by DanThomas64** [comment]
> Aren't you supposed to note which version for traceability ? Which release version is this planned for?

Meant to? No. Can we? Sure. This isn't our main platform for tracking this work so frequently these things get missed. If someone has the time and remembers to we will try and update that for you.

**Comment by Alablm** [comment]
Fixed in release 0.66.02
