### ISSUE TITLE
RTO Support bug 

### ISSUE THREAD

**Issue by Ghostlyshell617** [Savage-Game-Design/Mike-Force#9]
**Describe the bug**
RTO Support came in at the wrong angle, wiped almost our entire team and destroyed a huey.

**To Reproduce**
Called in a napalm strike with F-4 Phantom, heavy 
Roughly ~50 meters to the west of our current position where the entire team was at excluding pilots.

**Expected behaviour**
They were supposed to strike our west going from north to south, instead they came in east to west and dropped the payload on our position.
**Screenshots**

https://user-images.githubusercontent.com/47833072/117526183-0b4e6700-af89-11eb-810a-663e23ad1baf.mp4

Unfortunately it did not clip the part where we all got burned to death by napalm, but i managed to snag the clip where you can see us all respawning at base and then checking my radio to see if i actually called it in from the right angle which i did.

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): cam_lao_nam, macvsog

* [ ] Official Server
* [ ] Official InDev Server
* [X ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods: None.
    
Time the bug occurred (Please leave in GMT+0):  
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 
~7:30PM GMT+5

**Additional context**
Had been using the radio support for hours without issue, sometimes even danger close within 50 meters without issue until this point.

**Comment by Spoffy** [comment]
Thanks for the info on this! This is a CDLC issue most likely!

Would you mind opening an issue at https://feedback.bistudio.com/ for this? You can probably get away with just copy/pasting or linking to this issue!

Thanks in advance! :)
