### ISSUE TITLE
Bug: M1 carbine shoots 7.62x51

### ISSUE THREAD

**Issue by David-Ly-3990** [Savage-Game-Design/Mike-Force#90]
**Describe the bug**
The M1 carbine shoots 7.62x51 instead of 7.62x33

**To Reproduce**
It's always a constant

**Expected behaviour**
M1 carbine should shoot 7.62x33

**Screenshots**
![unknown](https://user-images.githubusercontent.com/20101307/118900146-41bba880-b8de-11eb-8498-cea36bb83752.png)

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): Bluefor on the Cam Lao Nam

* [X] Official Server
* [X] Official InDev Server
* [X] Private dedicated server
* [X] Private dedicated server with Headless client(s)
* [X] LAN Hosted

Additional mods:
None
Time the bug occurred (Please leave in GMT+0):
Constant
**Additional context**
None

**Comment by Alablm** [comment]
This github is in relation to the Mike Force game mode, not the S.O.G. Prarie Fire DLC. As the carbine is not defined by Mike Force, you'll have to direct your issue elsewhere, namely https://community.sogpf.com/threads/44-Bug-reporting
