### ISSUE TITLE
When Mission File Restarts, All Supplies in Buildings are Deleted and Buildings Decay.

### ISSUE THREAD

**Issue by Uptown0ne** [Savage-Game-Design/Mike-Force#91]
**Describe the bug**
When one restarts the mission file, upon loading back in all supplies in the various FOBs around the map disappear and all FOBs begin to decay.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
To reproduce the bug, all you must do is switch the mission file to another game mode, then switch back to the Mike Force gamemode. Set parameters and load into the game, then go to any FOBs around the map and check them to see if they have supplies. 

**Expected behaviour**
It is expected that all bases will not have supplies and they will begin to decay instantly upon starting the file. 

**Environment (please complete the following information):**
Version: v0.65.03
Map (specify if Altis Blufor): Cam Lao Nam

* [ ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [x] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
CBA_A3, Enhanced Movement, Task Force Arrowhead Radio (BETA!!!), Zeus Enhanced.

Time the bug occurred (Please leave in GMT+0):
If **Not** on an official server, please leave the time zone of your client for LAN or the server for dedicated: 
GMT-4, It's not an official server, you can switch mission files in this setting since it's set up to allow for switching mission files.

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Alablm** [comment]
Server restarts trigger this too. May be related to https://github.com/Savage-Game-Design/Mike-Force/issues/27

**Comment by Alablm** [comment]
A fix for this has been implemented in the latest internal version of Mike Force.

**Comment by Alablm** [comment]
Fixed in release 0.66.02
