### ISSUE TITLE
Configurable AA and Artillery density

### ISSUE THREAD

**Issue by BrightCandle** [Savage-Game-Design/Mike-Force#93]
Sometimes zones spawn with very dense placement of Artillery and Anti air that makes dealing with them really difficult. The artillery opens up very rapidly on infantry on the ground or the AA positions shoot at infantry from supporting positions requiring very fast action and attack and placement of satchels to destroy them. These positions are really difficult to take with air support due to the AA placement and by ground due to the artillery.

What ideally I would like is via parameter that allows limiting  the maximum density so that the number of artillery and AA within supporting distances (a kilometre) is limited to avoid insane and accurate barrages with very high levels of AA.

I think in general the placement of the AA and Artillery as it is around the periphery of the mission objective is a little suboptimal and makes very objective very similar feeling. Having some objectives with low AA and low Artillery would allow better use of vehicles in general for attacking the positions. Positions that are based on static weapons for example would be a nice third type of objective that is similar in style but has less problems with AA/Anti tank capabilities that the AA/Mortar's do.

**Comment by Spoffy** [comment]
We've got some plans to work on this in update 2 - it won't be the solution as you described it, but hopefully it solves your issue :)
