### ISSUE TITLE
Huey helicopter AFM

### ISSUE THREAD

**Issue by thelegend68** [Savage-Game-Design/Mike-Force#94]
Whenever attempting to lift any slung conex containers with huey helicopters in advanced flight model, aircraft stalls and crashes. Conex boxes never leave the ground.

Occurs on every server I have been on.

**Comment by aceb20** [comment]
After some testing, I can confirm that this is a CDLC issue, not a Mike Force issue. I'm going to pass this along to the team, though, thanks!

**Comment by aceb20** [comment]
After some testing, I can confirm that this is a CDLC issue, not a Mike Force issue. I'm going to pass this along to the team, though, thanks!

**Comment by aceb20** [comment]
After some testing, I can confirm that this is a CDLC issue, not a Mike Force issue. With CDLC issues, I'd ask if you'd make a ticket on the feedback tracker for the team to properly see: https://community.sogpf.com/threads/44-Bug-reporting

**Comment by Spoffy** [comment]
This should be sorted! :)
