### ISSUE TITLE
Building FOBs Inside AO

### ISSUE THREAD

**Issue by Dealman** [Savage-Game-Design/Mike-Force#95]
While I _do_ like defending a position against waves of enemies, I feel like being able to build FOBs directly inside an AO really removes a lot of the fun and more specifically _difficulty_. If you have a FOB inside an AO, you're all set - you can just respawn over and over.

Really, the only thing you end up fighting is the scheduled restart ;)

Instead of establishing neat FOBs somewhere outside, the meta is now to rush straight into the AO and immediately set up a respawn point and a few sandbag walls.

This also eliminates the need for troop transports, since they can just respawn and spawn on the FOB whilst keeping their gear.

**Comment by Spoffy** [comment]
Agreed - this is definitely an easy-mode strategy. We'll think of ways to counter this, but I don't think preventing FOB building is it! :)
