### ISSUE TITLE
Helicopters flip-over when lifting objects

### ISSUE THREAD

**Issue by rogerxx** [Savage-Game-Design/Mike-Force#97]
**Describe the bug**
Helicopters have a tendency to flip-over while lifting objects.  The flip will be extremely far to quick, than in real life, while flying flat and level at just above 150 km/hour.

**To Reproduce**
Fly helicopter while lifting object, cruise at safe altitude, at about or slightly more than 150 km/hour 

**Expected behaviour**
Helicopter will flip while flying flat & level, into an up-side down and usually repeat until collision.  Can immediately escape if eject the lift object.  Again, the recourse will be extremely quick, unlike in real life.  If the lift object is not ejected, a collision or explosion will result within one to two seconds 

**Screenshots**
none yet.

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor): 

* [ X ] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
 None
   
Time the bug occurred (Please leave in GMT+0):
Many times.

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by rogerxx** [comment]
ARMA 3 log file:
[arma3_x64_2021-05-29_17-33-19.zip](https://github.com/Savage-Game-Design/Mike-Force/files/6565361/arma3_x64_2021-05-29_17-33-19.zip)

**Comment by rogerxx** [comment]
flip-20210529.mp4 video

https://user-images.githubusercontent.com/2716501/120086821-42a7c380-c0b0-11eb-8e79-9a52a1d6918e.mp4

**Comment by rogerxx** [comment]
This bug may have something to do with server desync and lag, possibly induced by building too many bridges.  I've only heard building too many bridges  causes game server lag last night.  However, I just logged into server #1 several times tonight and  initially witnessed large amounts of built bridges, and now subsequently I am experiencing this flipping bug even upon slow approaches to the AO.  The chopper starts to witness large amounts of imbalance or toppling, as if the chopper is forgetting which end is up.  Possibly only seen when using advanced flight controls.

**Comment by rogerxx** [comment]
A full size original video clip using only ffmpeg vcodec/acodec copy, with -ss and -to parameters.

The previous flip-20210529.mp4 was created using OpenShot rather than commandline ffmpeg.

flip-fs-20210529.mp4

https://user-images.githubusercontent.com/2716501/120116485-6291c280-c156-11eb-8e19-f858c947f574.mp4

**Comment by rogerxx** [comment]
Think I just realized what maybe happening, upon server/client desync / de-synchronization, atypically the payload being lift may slingshot or might be temporarily putting more lift weight onto the vehicle lifting when using NVidia PhysX effects?  This could possibly occur instantaneously, making the lift vehicle also  instantaneously flip.  Speculative, if this is not intended effects, but very possible.

As you can see from the timeline of my reporting here, server lag seemed to induce the tipsy-topsy or unbalancing of the helicopter while approaching the AO with many bridges built, even at very very slow speeds, the unbalancing or flipping became very slow-motion and uncontrollable flipping, unless the load were immediately detached.

Advanced Helicopter Flight Model may also be significantly inducing unbalancing, due to the advanced flight model effects.

**Comment by Dealman** [comment]
Wasn't it reported elsewhere that slingroping using the advanced flight model is bugged in SOG? I use the simple model personally and have never, ever experienced this.

**Comment by Spoffy** [comment]
Flagged this as a CDLC issue for the core CDLC team to look into!

**Comment by rogerxx** [comment]
As far as I know, still experiencing this problem; although I now rarely ever exceed ~150-160 km/hour while sling loading and using advanced flight model.

**Comment by Alablm** [comment]
Closing - CDLC
