### ISSUE TITLE
M149 Water Buffalo bugs out entire building system

### ISSUE THREAD

**Issue by WolfairCorp** [Savage-Game-Design/Mike-Force#98]
**Describe the bug**
Trying to place an M149 Water Buffalo (decorative) will delay all your buildings by 1.

**To Reproduce**
Trying to place the M149 Water Buffalo. It will fail the first time. 

**Expected behavior**
Every building you place after will be delayed. So if after failing to build the buffalo you want to place a bunker, it will place a buffalo instead. If after that you place a guard tower, it will place a bunker, etc.

**Screenshots**
Full bug reproduction video. Building bug reproducing starts at 2:04
https://youtu.be/KmSjdjsImYE?t=124

**Environment (please complete the following information):**
Version: Latest
Map (specify if Altis Blufor): Cam Lao Nam

Bug verified on:
[ ] Official Server
[ ] Official InDev Server
[X] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[X] LAN Hosted

Additional mods: None
    
Time the bug occurred (Please leave in GMT+0): 17h GMT
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: Don't know.

**Additional context**
Nothing to add, but the building should be disabled for now, because since we don't have any deconstruction tools having the wrong buildings at the wrong place is a problem.

If you were LAN hosting, please attach your client RPT file from when the bug occurred, If on a private dedicated server, please attach the server's RPT from when the bug occurred.

The client did not produce an RPT file.

**Comment by Alablm** [comment]
Closing as this has been fixed
