### ISSUE TITLE
Building - Tools for the Right Job

### ISSUE THREAD

**Issue by TrevorKinard** [Savage-Game-Design/Mike-Force#99]
**Is your feature request related to a problem? Please describe.**
No it is not but, building so far is done through the use of placing the structure from the list, providing supplies, and hitting it with a shovel.

**Describe the solution you'd like**
I propose that depending on the building different tools should be used.

For things of a trench nature or general ground moving, a shovel should be used for construction.
For things that are actual buildings, a hammer should be used for construction.

**Additional context**
Would be nice but not required, give the axe type tools a use by allowing the ability to chop down trees for easy mobile resources for constructing buildings or to have it be the tool for dissembling placed buildings for a small regain of the resources used on it.

**Comment by Spoffy** [comment]
We're currently doing some work around improving tools - I think you'll be happy with what we're doing, for the most part! The only thing is we don't have plans currently to split buildings between shovel/hammer/etc, as it's a pain in the ass for people to do - even if it's more realistic! :)
